#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Vorssaint
#
# WP-00 spike: copy the candidate Vorssaint sources into the spike package so
# the spike is reproducible from the repository at any commit. Nothing is
# generated by hand; re-run this after editing files-clean.txt / files-all.txt.
#
#   ./sync.sh          # refresh both vendored trees
#
# Exactly one source rewrite is performed, and it is listed here so the
# "compiles unmodified" claim stays honest:
#
#   import Carbon.HIToolbox  ->  import Carbon
#
# because SwiftPM target names cannot contain a dot, so the Carbon shim
# module cannot be called `Carbon.HIToolbox`. No other byte is changed.

set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"

sync_one() {
    local manifest="$1" dest="$2" count=0
    rm -rf "$dest"
    mkdir -p "$dest"
    while IFS= read -r rel; do
        [ -n "$rel" ] || continue
        local src="$repo/$rel"
        if [ ! -f "$src" ]; then
            echo "sync.sh: missing $rel" >&2
            exit 1
        fi
        # Flatten: basenames are unique across the candidate set (checked below).
        local out="$dest/$(basename "$rel")"
        if [ -e "$out" ]; then
            echo "sync.sh: basename collision on $(basename "$rel")" >&2
            exit 1
        fi
        sed 's/^import Carbon\.HIToolbox$/import Carbon/' "$src" > "$out"
        count=$((count + 1))
    done < "$here/$manifest"
    echo "sync.sh: $manifest -> $dest ($count files)"
}

sync_one files-clean.txt "$here/Sources/VorssaintCoreSpike/Vendored"
sync_one files-all.txt   "$here/Sources/VorssaintCoreWide/Vendored"
