#include "rules.h"

#include <linux/input-event-codes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MS_NS(ms) ((uint64_t)(ms) * 1000000ULL)

void rules_config_defaults(rules_config *cfg)
{
    memset(cfg, 0, sizeof(*cfg));
    cfg->tap_threshold_ns = MS_NS(200);
    cfg->chatter_window_ns = MS_NS(40);
    cfg->tap_source = KEY_CAPSLOCK;
    cfg->tap_output = KEY_ESC;
    cfg->hold_output = KEY_LEFTCTRL;
    cfg->tap_hold_enabled = true;
    cfg->chatter_enabled = true;
}

void rules_init(rules_state *st, const rules_config *cfg)
{
    memset(st, 0, sizeof(*st));
    if (cfg)
        st->cfg = *cfg;
    else
        rules_config_defaults(&st->cfg);
    st->tap_state = TAP_IDLE;
}

const char *rules_tap_state_name(rules_tap_state s)
{
    switch (s) {
    case TAP_IDLE: return "idle";
    case TAP_PENDING: return "pending";
    case TAP_HOLD: return "hold";
    }
    return "?";
}

static int emit(rules_event *out, int cap, int n, uint16_t type, uint16_t code, int32_t value)
{
    if (n >= cap)
        return -1;
    out[n].type = type;
    out[n].code = code;
    out[n].value = value;
    return n + 1;
}

int rules_reconfigure(rules_state *st, const rules_config *cfg, rules_event *out, int out_cap)
{
    int n = 0;
    if (st->tap_state == TAP_HOLD)
        n = emit(out, out_cap, n, EV_KEY, st->cfg.hold_output, 0);
    if (n < 0)
        return -1;
    st->cfg = *cfg;
    st->tap_state = TAP_IDLE;
    st->tap_press_ns = 0;
    st->stat_out += (uint64_t)n;
    return n;
}

/* Rule 2, applied first because it models a hardware defect: a key switch that
 * bounces re-presses within a few milliseconds of its own release. A press
 * inside the window is dropped, and so is the release that closes it, so the
 * downstream key state stays balanced. Autorepeat (value 2) is generated by
 * the kernel, never by the switch, so it passes untouched. */
static bool chatter_should_drop(rules_state *st, const rules_event *in, uint64_t now_ns)
{
    if (!st->cfg.chatter_enabled || in->type != EV_KEY || in->code > RULES_KEY_MAX)
        return false;

    if (in->value == 1) {
        if (st->seen_release[in->code] &&
            now_ns - st->last_release_ns[in->code] < st->cfg.chatter_window_ns) {
            st->drop_next_release[in->code] = true;
            st->stat_chatter_dropped++;
            return true;
        }
        return false;
    }

    if (in->value == 0) {
        if (st->drop_next_release[in->code]) {
            st->drop_next_release[in->code] = false;
            st->stat_chatter_dropped++;
            /* The dropped release still marks when the switch opened, so a
             * burst of bounces is suppressed as a whole rather than every
             * other edge. */
            st->last_release_ns[in->code] = now_ns;
            st->seen_release[in->code] = true;
            return true;
        }
        st->last_release_ns[in->code] = now_ns;
        st->seen_release[in->code] = true;
        return false;
    }

    return false;
}

/* Rule 1: tap the source key for Escape, hold it for Control. The press is
 * withheld until the outcome is known, which is what makes the key usable as
 * a modifier: pressing any other key resolves it to a hold immediately, and
 * the clock resolves it after tap_threshold_ns if nothing else happens. */
static int tap_hold(rules_state *st, const rules_event *in, uint64_t now_ns, rules_event *out, int cap)
{
    int n = 0;

    if (in->type != EV_KEY) {
        /* Pointer motion and wheel do not resolve a pending hold: a tap-hold
         * key must survive an incidental mouse move. */
        return emit(out, cap, n, in->type, in->code, in->value);
    }

    if (in->code == st->cfg.tap_source) {
        switch (in->value) {
        case 1: /* press */
            if (st->tap_state == TAP_IDLE) {
                st->tap_state = TAP_PENDING;
                st->tap_press_ns = now_ns;
            }
            return 0;
        case 2: /* autorepeat on the source key is meaningless once remapped */
            return 0;
        case 0: /* release */
            if (st->tap_state == TAP_PENDING) {
                if (now_ns - st->tap_press_ns < st->cfg.tap_threshold_ns) {
                    n = emit(out, cap, n, EV_KEY, st->cfg.tap_output, 1);
                    if (n < 0) return -1;
                    n = emit(out, cap, n, EV_KEY, st->cfg.tap_output, 0);
                    st->stat_taps++;
                } else {
                    /* Held past the threshold but the timer had not run yet
                     * (no poll wakeup); emit the whole modifier press here. */
                    n = emit(out, cap, n, EV_KEY, st->cfg.hold_output, 1);
                    if (n < 0) return -1;
                    n = emit(out, cap, n, EV_KEY, st->cfg.hold_output, 0);
                    st->stat_holds++;
                }
            } else if (st->tap_state == TAP_HOLD) {
                n = emit(out, cap, n, EV_KEY, st->cfg.hold_output, 0);
            }
            st->tap_state = TAP_IDLE;
            st->tap_press_ns = 0;
            return n;
        default:
            return 0;
        }
    }

    /* Any other key. A fresh press while the decision is pending means the
     * user is using the key as a modifier, so resolve to hold before letting
     * the key through. A release does not resolve: it may belong to a key
     * pressed before the source key went down. */
    if (st->tap_state == TAP_PENDING && in->value == 1) {
        n = emit(out, cap, n, EV_KEY, st->cfg.hold_output, 1);
        if (n < 0) return -1;
        st->tap_state = TAP_HOLD;
        st->stat_holds++;
    }
    return emit(out, cap, n, in->type, in->code, in->value);
}

int rules_process(rules_state *st, const rules_event *in, uint64_t now_ns, rules_event *out, int out_cap)
{
    int n;

    if (in->type == EV_SYN)
        return 0; /* the output device re-syncs after every batch */

    st->stat_in++;

    if (chatter_should_drop(st, in, now_ns))
        return 0;

    if (!st->cfg.tap_hold_enabled) {
        n = emit(out, out_cap, 0, in->type, in->code, in->value);
    } else {
        n = tap_hold(st, in, now_ns, out, out_cap);
    }

    if (n > 0)
        st->stat_out += (uint64_t)n;
    return n;
}

uint64_t rules_deadline_ns(const rules_state *st)
{
    if (st->cfg.tap_hold_enabled && st->tap_state == TAP_PENDING)
        return st->tap_press_ns + st->cfg.tap_threshold_ns;
    return 0;
}

int rules_timer(rules_state *st, uint64_t now_ns, rules_event *out, int out_cap)
{
    uint64_t deadline = rules_deadline_ns(st);
    int n;

    if (deadline == 0 || now_ns < deadline)
        return 0;

    n = emit(out, out_cap, 0, EV_KEY, st->cfg.hold_output, 1);
    if (n < 0)
        return -1;
    st->tap_state = TAP_HOLD;
    st->stat_holds++;
    st->stat_out += (uint64_t)n;
    return n;
}

/* --- tiny JSON reader ------------------------------------------------------
 * The helper runs as root and parses a string handed to it over D-Bus, so it
 * does not link a JSON library: this reads exactly the seven keys of the rule
 * schema and rejects anything else it cannot account for. */

static const char *json_find(const char *json, const char *key)
{
    size_t klen = strlen(key);
    const char *p = json;
    while ((p = strchr(p, '"')) != NULL) {
        if (strncmp(p + 1, key, klen) == 0 && p[1 + klen] == '"') {
            p = p + 1 + klen + 1;
            while (*p == ' ' || *p == '\t' || *p == '\n')
                p++;
            if (*p != ':')
                return NULL;
            p++;
            while (*p == ' ' || *p == '\t' || *p == '\n')
                p++;
            return p;
        }
        p++;
    }
    return NULL;
}

static int json_bool(const char *json, const char *key, bool *out)
{
    const char *v = json_find(json, key);
    if (!v)
        return 0;
    if (strncmp(v, "true", 4) == 0) { *out = true; return 1; }
    if (strncmp(v, "false", 5) == 0) { *out = false; return 1; }
    return -1;
}

static int json_uint(const char *json, const char *key, unsigned long *out, unsigned long max)
{
    const char *v = json_find(json, key);
    char *end;
    unsigned long n;
    if (!v)
        return 0;
    if (*v < '0' || *v > '9')
        return -1;
    n = strtoul(v, &end, 10);
    if (end == v || n > max)
        return -1;
    *out = n;
    return 1;
}

int rules_config_from_json(const char *json, rules_config *cfg, char *err, size_t err_cap)
{
    unsigned long n;
    const char *bad = NULL;

    if (!json) {
        snprintf(err, err_cap, "not a JSON object");
        return -1;
    }
    /* Length before content: the reader walks the string once per key, so the
     * bound has to be applied before any of that work is done. */
    if (strnlen(json, RULES_JSON_MAX + 1) > RULES_JSON_MAX) {
        snprintf(err, err_cap, "document is longer than the %d byte limit", RULES_JSON_MAX);
        return -1;
    }
    if (strchr(json, '{') == NULL) {
        snprintf(err, err_cap, "not a JSON object");
        return -1;
    }
    rules_config_defaults(cfg);

    if (json_bool(json, "tap_hold", &cfg->tap_hold_enabled) < 0) bad = "tap_hold";
    if (!bad && json_bool(json, "chatter", &cfg->chatter_enabled) < 0) bad = "chatter";
    if (!bad && json_uint(json, "tap_threshold_ms", &n, 5000) < 0) bad = "tap_threshold_ms";
    else if (!bad && json_find(json, "tap_threshold_ms")) cfg->tap_threshold_ns = MS_NS(n);
    if (!bad && json_uint(json, "chatter_ms", &n, 1000) < 0) bad = "chatter_ms";
    else if (!bad && json_find(json, "chatter_ms")) cfg->chatter_window_ns = MS_NS(n);
    if (!bad && json_uint(json, "tap_source", &n, RULES_KEY_MAX) < 0) bad = "tap_source";
    else if (!bad && json_find(json, "tap_source")) cfg->tap_source = (uint16_t)n;
    if (!bad && json_uint(json, "tap_output", &n, RULES_KEY_MAX) < 0) bad = "tap_output";
    else if (!bad && json_find(json, "tap_output")) cfg->tap_output = (uint16_t)n;
    if (!bad && json_uint(json, "hold_output", &n, RULES_KEY_MAX) < 0) bad = "hold_output";
    else if (!bad && json_find(json, "hold_output")) cfg->hold_output = (uint16_t)n;

    if (bad) {
        snprintf(err, err_cap, "bad value for \"%s\"", bad);
        return -1;
    }
    return 0;
}

int rules_state_to_json(const rules_state *st, char *buf, size_t cap)
{
    return snprintf(buf, cap,
                    "{\"tap_hold\":%s,\"tap_threshold_ms\":%llu,\"chatter\":%s,"
                    "\"chatter_ms\":%llu,\"tap_source\":%u,\"tap_output\":%u,"
                    "\"hold_output\":%u,\"tap_state\":\"%s\","
                    "\"in\":%llu,\"out\":%llu,\"chatter_dropped\":%llu,"
                    "\"taps\":%llu,\"holds\":%llu}",
                    st->cfg.tap_hold_enabled ? "true" : "false",
                    (unsigned long long)(st->cfg.tap_threshold_ns / 1000000ULL),
                    st->cfg.chatter_enabled ? "true" : "false",
                    (unsigned long long)(st->cfg.chatter_window_ns / 1000000ULL),
                    st->cfg.tap_source, st->cfg.tap_output, st->cfg.hold_output,
                    rules_tap_state_name(st->tap_state),
                    (unsigned long long)st->stat_in, (unsigned long long)st->stat_out,
                    (unsigned long long)st->stat_chatter_dropped,
                    (unsigned long long)st->stat_taps, (unsigned long long)st->stat_holds);
}
