// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedClipboardAutoClearTimingTests: XCTestCase {
    func testClipboardAutoClearTiming() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let autoClearCopiedAt = Date(timeIntervalSince1970: 1_000_000)

        expect(ClipboardAutoClearSupport.decide(changeCount: 8,
                                                lastChangeCount: 7,
                                                lastClearedChangeCount: 0,
                                                lastChangeDate: autoClearCopiedAt,
                                                now: autoClearCopiedAt.addingTimeInterval(600),
                                                delay: 20) == .noteChange,
               "a new change count restarts the clock however long the old content sat there")

        expect(ClipboardAutoClearSupport.decide(changeCount: 7,
                                                lastChangeCount: 7,
                                                lastClearedChangeCount: 0,
                                                lastChangeDate: autoClearCopiedAt,
                                                now: autoClearCopiedAt.addingTimeInterval(19),
                                                delay: 20) == .wait,
               "unchanged content waits until the delay is up")

        expect(ClipboardAutoClearSupport.decide(changeCount: 7,
                                                lastChangeCount: 7,
                                                lastClearedChangeCount: 0,
                                                lastChangeDate: autoClearCopiedAt,
                                                now: autoClearCopiedAt.addingTimeInterval(20),
                                                delay: 20) == .clear,
               "unchanged content clears once the delay is exactly up")

        expect(ClipboardAutoClearSupport.decide(changeCount: 7,
                                                lastChangeCount: 7,
                                                lastClearedChangeCount: 0,
                                                lastChangeDate: autoClearCopiedAt,
                                                now: autoClearCopiedAt.addingTimeInterval(8 * 3_600),
                                                delay: 20) == .clear,
               "waking after hours of sleep clears at once instead of waiting out another delay")

        expect(ClipboardAutoClearSupport.decide(changeCount: 7,
                                                lastChangeCount: 7,
                                                lastClearedChangeCount: 7,
                                                lastChangeDate: autoClearCopiedAt,
                                                now: autoClearCopiedAt.addingTimeInterval(600),
                                                delay: 20) == .wait,
               "the count our own clear produced never clears again, so clearing cannot loop")

        expect(ClipboardAutoClearSupport.clearIsAuthorized(enqueuedGeneration: 3,
                                                           currentGeneration: 3,
                                                           featureIsAvailable: true,
                                                           triggerIsEnabled: true)
               && !ClipboardAutoClearSupport.clearIsAuthorized(enqueuedGeneration: 3,
                                                                currentGeneration: 4,
                                                                featureIsAvailable: true,
                                                                triggerIsEnabled: true)
               && !ClipboardAutoClearSupport.clearIsAuthorized(enqueuedGeneration: 3,
                                                                currentGeneration: 3,
                                                                featureIsAvailable: true,
                                                                triggerIsEnabled: false),
               "a queued clear is invalidated when its setting changes before pasteboard access")

        expect(FeatureStrings.clipboard(.ptBR).shortcutHint.contains("colar no app anterior"),
               "clipboard shortcut hint exposes row click paste in Portuguese")

        expect(FeatureStrings.clipboard(.ptBR).shortcutHint.contains("⌘+clique seleciona"),
               "clipboard shortcut hint exposes command click multi-select in Portuguese")

        expect(FeatureStrings.clipboard(.ptBR).clickRowShortcut == "Clique na linha",
               "clipboard visual shortcut exposes row click in Portuguese")

        expect(FeatureStrings.clipboard(.enUS).shortcutHint.contains("paste it into the previous app"),
               "clipboard shortcut hint exposes row click paste in English")

        expect(FeatureStrings.clipboard(.enUS).shortcutHint.contains("⌘-click selects"),
               "clipboard shortcut hint exposes command click multi-select in English")

        expect(FeatureStrings.clipboard(.enUS).commandClickShortcut == "⌘ Click",
               "clipboard visual shortcut exposes command click in English")

        expect(FeatureStrings.clipboard(.tr).shortcutHint.contains("yapıştırın"),
               "clipboard shortcut hint exposes row click paste in Turkish")

        expect(FeatureStrings.clipboard(.tr).shortcutHint.contains("birden çok öğe seçer"),
               "clipboard shortcut hint exposes command click multi-select in Turkish")

        expect(FeatureStrings.clipboard(.tr).clickRowShortcut == "Satıra tıkla",
               "clipboard visual shortcut exposes row click in Turkish")

        let featureTitles: [(AppLanguage, String, String, String, String)] = [
            (.enUS, "Clipboard", "Window layout", "Utilities", "Alerts"),
            (.ptBR, "Clipboard", "Layout de janelas", "Utilitários", "Alertas"),
            (.tr, "Pano", "Pencere yerleşimi", "Araçlar", "Uyarılar"),
            (.es, "Portapapeles", "Diseño de ventanas", "Utilidades", "Alertas"),
            (.de, "Zwischenablage", "Fensterlayout", "Dienstprogramme", "Warnungen"),
            (.fr, "Presse-papiers", "Disposition des fenêtres", "Utilitaires", "Alertes"),
            (.it, "Appunti", "Layout finestre", "Utilità", "Avvisi"),
            (.ja, "クリップボード", "ウインドウ配置", "ユーティリティ", "アラート"),
            (.ko, "클립보드", "윈도우 정렬", "유틸리티", "알림"),
            (.ru, "Буфер обмена", "Раскладка окон", "Утилиты", "Оповещения"),
            (.zhHans, "剪贴板", "窗口布局", "实用工具", "提醒"),
            (.zhTW, "剪貼簿", "視窗排列", "工具程式", "提醒"),
            (.zhHK, "剪貼簿", "視窗排列", "工具", "提示"),
        ]

        for (language, clipboardTitle, windowTitle, utilitiesTitle, alertsTitle) in featureTitles {
            expect(FeatureStrings.clipboard(language).title == clipboardTitle,
                   "\(language.rawValue) clipboard title is localized")
            expect(FeatureStrings.windowLayout(language).title == windowTitle,
                   "\(language.rawValue) window layout title is localized")
            expect(FeatureStrings.settingsCategories(language).utilities == utilitiesTitle,
                   "\(language.rawValue) settings category title is localized")
            expect(FeatureStrings.monitorAlerts(language).section == alertsTitle,
                   "\(language.rawValue) monitor alert section is localized")
        }

        for language in AppLanguage.allCases {
            let clipboardStrings = FeatureStrings.clipboard(language)
            expectFormat(clipboardStrings.pasteSelectedFormat, ["d"],
                         "\(language.rawValue) paste-selected button format")
            expectFormat(clipboardStrings.copySelectedFormat, ["d"],
                         "\(language.rawValue) copy-selected button format")
            expect(!clipboardStrings.autoClearEnable.isEmpty
                   && !clipboardStrings.autoClearSecondsSuffix.isEmpty
                   && !clipboardStrings.autoClearOnSleep.isEmpty
                   && !clipboardStrings.autoClearOnDisplaySleep.isEmpty
                   && !clipboardStrings.autoClearOnScreenLock.isEmpty
                   && !clipboardStrings.autoClearCaption.isEmpty,
                   "\(language.rawValue) clipboard auto clear labels are localized")
            let layoutStrings = FeatureStrings.windowLayout(language)
            expect(!layoutStrings.sixths.isEmpty
                   && !layoutStrings.topLeftSixth.isEmpty
                   && !layoutStrings.topCenterSixth.isEmpty
                   && !layoutStrings.topRightSixth.isEmpty
                   && !layoutStrings.bottomLeftSixth.isEmpty
                   && !layoutStrings.bottomCenterSixth.isEmpty
                   && !layoutStrings.bottomRightSixth.isEmpty,
                   "\(language.rawValue) window sixth layout labels are localized")
            expect(!layoutStrings.gestureSection.isEmpty
                   && !layoutStrings.gestureEnable.isEmpty
                   && !layoutStrings.gestureCaption.isEmpty
                   && !layoutStrings.gestureModifiers.isEmpty
                   && !layoutStrings.gestureMove.isEmpty
                   && !layoutStrings.gestureResize.isEmpty
                   && !layoutStrings.gestureResizeHint.isEmpty
                   && !layoutStrings.gestureRaiseWindow.isEmpty,
                   "\(language.rawValue) window gesture controls are localized")
            expect(!layoutStrings.edgeSnapEnable.isEmpty
                   && !layoutStrings.edgeSnapCaption.isEmpty
                   && !layoutStrings.edgeSnapSystemConflict.isEmpty
                   && !layoutStrings.edgeSnapOpenSystemSettings.isEmpty
                   && !layoutStrings.edgeSnapWaitingForSystem.isEmpty
                   && !layoutStrings.edgeSnapEnable.contains("—")
                   && !layoutStrings.edgeSnapCaption.contains("—")
                   && !layoutStrings.edgeSnapSystemConflict.contains("—")
                   && !layoutStrings.edgeSnapOpenSystemSettings.contains("—")
                   && !layoutStrings.edgeSnapWaitingForSystem.contains("—"),
                   "\(language.rawValue) window edge snap controls are localized")
            let alertStrings = FeatureStrings.monitorAlerts(language)
            expect(alertStrings.caption.contains("12"),
                   "\(language.rawValue) monitor alert caption explains the sustained alert window")
            expectFormat(alertStrings.cpuBodyFormat, ["d"], "\(language.rawValue) CPU alert format")
            expectFormat(alertStrings.cpuTemperatureBodyFormat, ["d"],
                         "\(language.rawValue) CPU temperature alert format")
            expectFormat(alertStrings.diskBodyFormat, ["@", "d"], "\(language.rawValue) disk alert format")
            expectFormat(alertStrings.batteryBodyFormat, ["d"], "\(language.rawValue) battery alert format")
            expectFormat(alertStrings.batteryTemperatureBodyFormat, ["d"],
                         "\(language.rawValue) battery temperature alert format")
        }

        expect(FeatureStrings.monitorAlerts(.enUS).cooldown == "Repeat the same alert after",
               "English monitor repeat control is explicit")

        expect(FeatureStrings.monitorAlerts(.ptBR).cooldown == "Repetir o mesmo alerta depois de",
               "Portuguese monitor repeat control is explicit")

        print("[generated-checks] ClipboardAutoClearTiming \(checks)")
    }
}
