// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedCommandBarCalculatorTests: XCTestCase {
    func testCommandBarCalculator() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        func math(_ input: String, decimal: String = ".", grouping: String = ",") -> String? {
            CommandBarMath.evaluate(input,
                                    decimalSeparator: decimal,
                                    groupingSeparator: grouping,
                                    locale: Locale(identifier: "en_US"))?.formatted
        }

        func mathValue(_ input: String, decimal: String = ".", grouping: String = ",") -> Double? {
            CommandBarMath.evaluate(input,
                                    decimalSeparator: decimal,
                                    groupingSeparator: grouping,
                                    locale: Locale(identifier: "en_US"))?.value
        }

        expect(math("2+2") == "4", "the calculator answers a sum")

        expect(math("10 * 4.5") == "45", "spaces and decimals are fine")

        expect(math("(2+3)*4") == "20", "parentheses come first")

        expect(math("2+3*4") == "14", "multiplication binds tighter than addition")

        expect(math("10/4") == "2.5", "division keeps its decimals")

        expect(math("2^3^2") == "512", "powers group to the right")

        expect(math("-5+2") == "-3", "a leading minus is a sign, not an error")

        expect(math("--5+1") == "6", "two minuses cancel")

        expect(math("1920/2") == "960", "the everyday case works")

        expect(mathValue("0.1+0.2") == 0.3 && math("0.1+0.2") == "0.3",
               "floating point noise never reaches the eye")

        expect(math("1,000+1") == "1,001", "grouped thousands parse and print grouped")

        expect(math("2 x 3") == "6" && math("10 ÷ 2") == "5" && math("2 × 3") == "6",
               "the written multiplication and division signs work too")

        expect(math("2(3+4)") == "14" && math("(1+2)(3+4)") == "21",
               "a number against a parenthesis multiplies")

        expect(math("-2^2") == "-4", "a sign applies to the whole power, as on paper")

        expect(math("2^0.5")?.hasPrefix("1.41421") == true, "a fractional power is fine")

        expect(math("1/1000000000") == "1e-9", "a billionth reads as a billionth, not as zero")

        expect(math("2^100")?.contains("e") == true, "a huge answer switches notation instead of vanishing")

        expect(math("2026-07-27") == nil && math("27/07/2026") == nil && math("10:30") == nil,
               "a date or a time is never answered as a sum")

        expect(math("100-50") == "50", "two numbers around a minus are still a subtraction")

        expect(math("SDL_VIDEODRIVER=") == nil && math("x=5") == nil,
               "an assignment shape is not an expression")

        expect(math("7+3=") == "10", "a trailing equals sign is just habit")

        expect(math("480+15%") == "552", "a percentage after plus is relative")

        expect(math("480-15%") == "408", "and after minus too")

        expect(math("20% of 480") == "96", "percent of a number reads as it is said")

        expect(math("20% de 480") == "96", "the same in the other words people type")

        expect(math("50%") == nil, "a lone percentage is not a question")

        expect(math("200*10%") == "20", "a percentage multiplies as a fraction")

        expect(math("5") == nil, "a lone number is a search, not an answer")

        expect(math("hello") == nil, "words are not expressions")

        expect(math("1password") == nil, "an app name that starts with a digit stays a search")

        expect(math("volume 20") == nil, "a command with a number is not a sum")

        expect(math("brilho 40") == nil, "neither is the same command in another language")

        expect(math("10/0") == nil, "dividing by zero has no answer to show")

        expect(math("2+") == nil && math("(2+3") == nil && math("2++") == nil,
               "an unfinished expression stays quiet")

        expect(math("2 * -3") == "-6", "a sign after an operator is read as a sign")

        expect(math(String(repeating: "(", count: 60) + "1" + String(repeating: ")", count: 60)) == nil,
               "a wall of parentheses is refused instead of eating the stack")

        expect(math("e-mail") == nil, "a hyphenated word is not a subtraction")

        expect(math("9999999999999999*99")?.contains("e") == true,
               "a number past plain reading switches notation")

        // The same numbers as the owner's Mac writes them.
        expect(CommandBarMath.evaluate("1.234,5 + 1",
                                       decimalSeparator: ",",
                                       groupingSeparator: ".",
                                       locale: Locale(identifier: "pt_BR"))?.formatted == "1.235,5",
               "a comma decimal parses and prints back in the same shape")

        expect(CommandBarMath.evaluate("1,5*2",
                                       decimalSeparator: ",",
                                       groupingSeparator: ".",
                                       locale: Locale(identifier: "pt_BR"))?.value == 3,
               "the comma is the decimal point where that is the custom")

        expect(math("1.500+1", decimal: ",", grouping: ".") == "1,501",
               "three digits after the grouping separator read as thousands")

        print("[generated-checks] CommandBarCalculator \(checks)")
    }
}
