// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedHistoryRingBufferTests: XCTestCase {
    func testHistoryRingBuffer() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        var history = MetricHistory(capacity: 3)

        history.push(1)

        history.push(2)

        expect(history.values == [1, 2], "history keeps order under capacity")

        history.push(3)

        history.push(4)

        expect(history.values == [2, 3, 4], "history drops oldest at capacity")

        expect(history.values.count == 3, "history never exceeds capacity")

        expect(history.publishedValues(whileVisible: false).isEmpty
                && history.values == [2, 3, 4]
                && history.publishedValues(whileVisible: true) == [2, 3, 4],
               "hidden graphs publish no arrays without discarding their ring")

        var single = MetricHistory(capacity: 1)

        single.push(5)

        single.push(6)

        expect(single.values == [6], "capacity 1 keeps only newest")

        print("[generated-checks] HistoryRingBuffer \(checks)")
    }
}
