// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedQuickTogglesTests: XCTestCase {
    func testQuickToggles() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        expect(QuickTogglesSupport.emptyTrashSource == "tell application \"Finder\" to empty trash",
               "the Trash script asks the Finder and nothing else")

        expect(QuickTogglesSupport.isPermissionError(-1743)
                && QuickTogglesSupport.isPermissionError(-1744),
               "both Apple Event consent errors read as a permission problem")

        expect(!QuickTogglesSupport.isPermissionError(-1728)
                && !QuickTogglesSupport.isPermissionError(nil),
               "other script errors and success never read as a permission problem")

        expect(QuickTogglesSupport.finderFlag(true, default: false)
                && !QuickTogglesSupport.finderFlag(false, default: true),
               "real booleans win over the default")

        expect(QuickTogglesSupport.finderFlag("YES", default: false)
                && QuickTogglesSupport.finderFlag("true", default: false)
                && QuickTogglesSupport.finderFlag("1", default: false),
               "legacy YES, true and 1 strings read as on")

        expect(!QuickTogglesSupport.finderFlag("NO", default: true)
                && !QuickTogglesSupport.finderFlag("false", default: true)
                && !QuickTogglesSupport.finderFlag("0", default: true),
               "legacy NO, false and 0 strings read as off")

        expect(QuickTogglesSupport.finderFlag(nil, default: true)
                && !QuickTogglesSupport.finderFlag(nil, default: false)
                && QuickTogglesSupport.finderFlag("maybe", default: true),
               "absent or unreadable values fall back to the given default")

        expect(QuickTogglesSupport.shouldOfferEject(isInternal: false, isRemovable: true,
                                                    isEjectable: false, isLocal: true,
                                                    isRootFileSystem: false)
                && QuickTogglesSupport.shouldOfferEject(isInternal: false, isRemovable: false,
                                                        isEjectable: true, isLocal: true,
                                                        isRootFileSystem: false),
               "external removable or ejectable local volumes are offered")

        expect(QuickTogglesSupport.shouldOfferEject(isInternal: false, isRemovable: false,
                                                    isEjectable: false, isLocal: true,
                                                    isRootFileSystem: false),
               "an external drive with fixed media is offered, the common desk drive")

        expect(QuickTogglesSupport.shouldOfferEject(isInternal: true, isRemovable: true,
                                                    isEjectable: true, isLocal: true,
                                                    isRootFileSystem: false),
               "media that comes out of an internal reader is offered")

        expect(!QuickTogglesSupport.shouldOfferEject(isInternal: true, isRemovable: false,
                                                     isEjectable: false, isLocal: true,
                                                     isRootFileSystem: false),
               "internal fixed drives are never ejected")

        expect(!QuickTogglesSupport.shouldOfferEject(isInternal: false, isRemovable: true,
                                                     isEjectable: true, isLocal: false,
                                                     isRootFileSystem: false),
               "network volumes are never ejected")

        expect(!QuickTogglesSupport.shouldOfferEject(isInternal: false, isRemovable: true,
                                                     isEjectable: true, isLocal: true,
                                                     isRootFileSystem: true),
               "the volume the Mac booted from is never ejected, even on an external drive")

        expect(!QuickTogglesSupport.shouldOfferEject(isInternal: false, isRemovable: false,
                                                     isEjectable: true, isLocal: true,
                                                     isRootFileSystem: false,
                                                     volumeName: "Time Machine",
                                                     excludedVolumes: ["time machine"]),
               "a volume matching an excluded name case-insensitively is not offered for eject")

        expect(!QuickTogglesSupport.shouldOfferEject(isInternal: false, isRemovable: true,
                                                     isEjectable: true, isLocal: true,
                                                     isRootFileSystem: false,
                                                     volumeName: "SD Card",
                                                     volumeUUID: "1234-5678-ABCD",
                                                     excludedVolumes: ["1234-5678-abcd"]),
               "a volume matching an excluded UUID is not offered for eject")

        expect(QuickTogglesSupport.shouldOfferEject(isInternal: false, isRemovable: true,
                                                    isEjectable: true, isLocal: true,
                                                    isRootFileSystem: false,
                                                    volumeName: "USB Flash",
                                                    excludedVolumes: ["Time Machine"]),
               "a volume not on the exclusion list is offered for eject")

        print("[generated-checks] QuickToggles \(checks)")
    }
}
