// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedResultTests: XCTestCase {
    func testResult() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        // A UserDefaults suite leaves an empty plist in ~/Library/Preferences
        // even after `removePersistentDomain`, and cfprefsd writes that file
        // back out around the time this process exits, so the run cannot delete
        // it itself. `build.sh --test` clears them afterwards, by name prefix.
        // A suite named outside those prefixes survives every run instead.
        let testSource = (try? String(contentsOfFile: "Tests/MetricsTests.swift",
                                      encoding: .utf8)) ?? ""

        expect(!testSource.isEmpty, "the test file reads back for its own source checks")

        // The prefixes are read out of the sweep itself, so the check and the
        // thing it guards cannot drift apart.
        let buildScript = (try? String(contentsOfFile: "build.sh", encoding: .utf8)) ?? ""

        let sweepBody = buildScript.components(separatedBy: "discard_test_preferences() {")
            .dropFirst().first?.components(separatedBy: "\n}").first ?? ""

        let sweptNamespaces = sweepBody.components(separatedBy: "\"")
            .enumerated().filter { $0.offset % 2 == 1 }.map(\.element)
            .filter { $0.hasSuffix(".") }

        expect(!sweptNamespaces.isEmpty, "the swept namespaces read back out of build.sh")

        expect(sweepBody.contains("rm -f \"$preferences\"/$name*.plist(N)"),
               "the defaults preference sweep tolerates an already-empty namespace")

        // Split so this needle is not itself a match in the text it scans.
        let suiteCall = "UserDefaults(suiteName" + ": "

        let suiteArguments = testSource.components(separatedBy: suiteCall)
            .dropFirst()
            .map { String($0.prefix { $0 != ")" && $0 != "," && !$0.isNewline }) }

        expect(!suiteArguments.isEmpty, "the namespace check finds the suites it guards")

        for argument in Set(suiteArguments) {
            let name: String?
            if argument.hasPrefix("\"") {
                name = String(argument.dropFirst().prefix { $0 != "\"" })
            } else {
                name = testSource.components(separatedBy: "let \(argument) = \"")
                    .dropFirst().first
                    .map { String($0.prefix { $0 != "\"" }) }
            }
            expect(name.map { value in sweptNamespaces.contains { value.hasPrefix($0) } } == true,
                   "defaults suite \(argument) is named inside a namespace build.sh sweeps")
        }

        print("[generated-checks] Result \(checks)")
    }
}
