// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedAppMemoryTests: XCTestCase {
    func testAppMemory() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        // Carried over: state an earlier section of MetricsTests.swift set and this one inherits.
        MetricFormat.locale = Locale(identifier: "en_US_POSIX")

        let appUsed = MetricFormat.appMemory(totalBytes: 16 * 1024,
                                             pageSize: 1024,
                                             internalPages: 10,
                                             purgeablePages: 3)

        expect(appUsed == 7 * 1024, "app memory excludes purgeable pages from internal pages")

        expect(MetricFormat.appMemory(totalBytes: 16 * 1024, pageSize: 1024,
                                      internalPages: 2, purgeablePages: 5) == 0,
               "app memory is zero when purgeable pages exceed internal pages")

        expect(MetricFormat.appMemory(totalBytes: 16, pageSize: 1,
                                      internalPages: 100, purgeablePages: 0) == 16,
               "app memory clamps to total physical memory")

        expect(MetricFormat.appMemory(totalBytes: 0, pageSize: 1024,
                                      internalPages: 10, purgeablePages: 0) == 0,
               "app memory is zero when total is zero")

        expect(MetricFormat.appMemory(totalBytes: 16 * 1024, pageSize: 0,
                                      internalPages: 10, purgeablePages: 0) == 0,
               "app memory is zero when page size is zero")

        expect(MetricFormat.selectedMemory(used: 12, app: 7, metric: "app") == 7,
               "the shared memory selector returns app memory")

        expect(MetricFormat.selectedMemory(used: 12, app: 7, metric: "unknown") == 12,
               "an unknown shared memory selector falls back to used memory")

        expect(MetricFormat.compressedMemory(totalBytes: 16 * 1024, pageSize: 1024, compressorPages: 5)
               == 5 * 1024,
               "compressed memory is compressor pages in bytes")

        expect(MetricFormat.compressedMemory(totalBytes: 16, pageSize: 1, compressorPages: 100) == 16,
               "compressed memory clamps to total physical memory")

        expect(MetricFormat.compressedMemory(totalBytes: 0, pageSize: 1024, compressorPages: 5) == 0,
               "compressed memory is zero when total is zero")

        expect(MetricFormat.cachedFiles(totalBytes: 16 * 1024, pageSize: 1024, fileBackedPages: 3)
               == 3 * 1024,
               "cached files are file-backed pages in bytes")

        expect(MetricFormat.cachedFiles(totalBytes: 16, pageSize: 1, fileBackedPages: 100) == 16,
               "cached files clamp to total physical memory")

        expect(MetricFormat.cachedFiles(totalBytes: 16 * 1024, pageSize: 0, fileBackedPages: 3) == 0,
               "cached files are zero when page size is zero")

        print("[generated-checks] AppMemory \(checks)")
    }
}
