// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedScreenshotToolTests: XCTestCase {
    func testScreenshotTool() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        var scrollingStressPassed = true

        var unmatchedScrollPixels = [UInt8](repeating: 0, count: 16 * 120)

        for index in unmatchedScrollPixels.indices {
            unmatchedScrollPixels[index] = UInt8((index * 47 + index / 11) % 253)
        }

        var patternParts = DateComponents()

        patternParts.year = 2026

        patternParts.month = 7

        patternParts.day = 24

        patternParts.hour = 15

        patternParts.minute = 4

        patternParts.second = 9

        let captureMenuSuite = "com.vorssaint.tests.capture-menu.\(UUID().uuidString)"

        // A button says what it does. The empty zoom state had borrowed the
        // timeline lane's hint, so the button read "Click here to add a zoom"
        // while being the very thing the reader was already looking at.
        for language in AppLanguage.allCases {
            let recorder = FeatureStrings.recorder(language)
            expect(!recorder.addZoomButton.isEmpty
                    && recorder.addZoomButton != recorder.zoomLaneEmptyHint,
                   "the empty zoom state has its own button label in \(language.rawValue)")
        }

        // A menu row says where the command lives. Every Mac app has a menu
        // named after itself, so the app menu read its own name twice.
        expect(CommandBarMenuPath.crumb(appName: "Notes", path: ["Notes"]) == "Notes",
               "the app menu does not say the app name twice")

        expect(CommandBarMenuPath.crumb(appName: "Notes", path: ["File", "Export"])
                == "Notes \u{203A} File \u{203A} Export",
               "a real trail keeps every step")

        expect(CommandBarMenuPath.crumb(appName: "Notes", path: []) == "Notes",
               "a command straight off the app names only the app")

        expect(CommandBarMenuPath.crumb(appName: "Notes", path: ["", "View"])
                == "Notes \u{203A} View",
               "an empty step leaves no dangling separator")

        // Reading a file is not a drawing step. The watermark logo was being
        // decoded inside the preview's body, so every frame of an opacity
        // drag re-read it from disk; it is loaded once per chosen file now,
        // which is what a task is for.
        var decodingInBody: [String] = []

        for path in (try? FileManager.default.subpathsOfDirectory(atPath: "Sources/Vorssaint/UI")) ?? [] {
            guard path.hasSuffix(".swift") else { continue }
            let full = "Sources/Vorssaint/UI/" + path
            let lines = ((try? String(contentsOfFile: full, encoding: .utf8)) ?? "")
                .components(separatedBy: "\n")
            for (index, line) in lines.enumerated() {
                let reads = line.contains("NSImage(contentsOfFile:")
                    || line.contains("Data(contentsOf:")
                guard reads else { continue }
                let around = lines[max(0, index - 6)...min(lines.count - 1, index + 2)]
                if !around.contains(where: { $0.contains(".task(") || $0.contains("func ")
                                             || $0.contains("Task {") }) {
                    decodingInBody.append("\(full):\(index + 1)")
                }
            }
        }

        expect(decodingInBody.isEmpty,
               "a view reads a file once, never while drawing (\(decodingInBody.joined(separator: ", ")))")

        // A word pinned to a fixed column has to be allowed to give: the
        // backdrop sliders were labelled in a 64-point column that the Turkish
        // and Spanish words for blur run past, so they were being cut.
        let widestBackdropLabel = AppLanguage.allCases
            .flatMap { language -> [String] in
                let screenshot = FeatureStrings.screenshot(language)
                return [screenshot.backdropPaddingLabel,
                        screenshot.backdropCornersLabel,
                        screenshot.backdropBlurLabel]
            }
            .map(\.count).max() ?? 0

        expect(widestBackdropLabel >= 10,
               "the backdrop labels are long enough somewhere for the column to matter")

        for path in ["Sources/Vorssaint/UI/Screenshot/ScreenshotBackdropPopover.swift",
                     "Sources/Vorssaint/UI/Recorder/RecorderInspector.swift"] {
            let code = (try? String(contentsOfFile: path, encoding: .utf8)) ?? ""
            expect(!code.isEmpty, "the slider source reads back for its shape check")
            let pinned = code.components(separatedBy: "\n")
                .filter { $0.contains(".frame(width: 64, alignment: .leading)")
                          || $0.contains(".frame(width: 50, alignment: .leading)") }
            expect(!pinned.isEmpty, "the pinned label column is still there in \(path)")
            expect(code.components(separatedBy: "minimumScaleFactor(0.82)").count - 1 == pinned.count,
                   "every label pinned to that column may shrink instead of being cut (\(path))")
        }

        let fileDate = Date(timeIntervalSince1970: 1_752_486_065) // 2025-07-14 09:41:05 UTC

        let recentID = UUID()

        let dragRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent("ScreenshotDragTests-\(UUID().uuidString)", isDirectory: true)

        let dragData = Data([0x89, 0x50, 0x4E, 0x47])

        let copyRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent("ScreenshotCopyTests-\(UUID().uuidString)", isDirectory: true)

        let copySymlink = FileManager.default.temporaryDirectory
            .appendingPathComponent("ScreenshotCopyLink-\(UUID().uuidString)")

        print("[generated-checks] ScreenshotTool \(checks)")
    }
}
