// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedThePanelSurfaceReachesThePopoverArrowIssue1030Tests: XCTestCase {
    func testThePanelSurfaceReachesThePopoverArrowIssue1030() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let panelThemeSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/UI/Theme.swift",
            encoding: .utf8)) ?? ""

        let panelViewSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/UI/MenuPanel/MenuPanelView.swift",
            encoding: .utf8)) ?? ""

        let statusPlacementSuite = "com.vorssaint.tests.statusItemPlacement"

        let keyboardShortcutSettings: [String: Any] = [
            DefaultsKey.keyboardBrightnessShortcutsEnabled: true,
            DefaultsKey.keyboardBrightnessDecreaseShortcut: "control+command:27",
            DefaultsKey.keyboardBrightnessIncreaseShortcut: "control+command:24",
        ]

        let assignedLayoutShortcutKeys = [
            DefaultsKey.windowLayoutShortcutLeft,
            DefaultsKey.windowLayoutShortcutRight,
            DefaultsKey.windowLayoutShortcutTop,
            DefaultsKey.windowLayoutShortcutBottom,
            DefaultsKey.windowLayoutShortcutTopLeft,
            DefaultsKey.windowLayoutShortcutTopRight,
            DefaultsKey.windowLayoutShortcutBottomLeft,
            DefaultsKey.windowLayoutShortcutBottomRight,
            DefaultsKey.windowLayoutShortcutMaximize,
            DefaultsKey.windowLayoutShortcutCenter,
            DefaultsKey.windowLayoutShortcutRestore,
            DefaultsKey.windowLayoutShortcutLeftThird,
            DefaultsKey.windowLayoutShortcutCenterThird,
            DefaultsKey.windowLayoutShortcutRightThird,
            DefaultsKey.windowLayoutShortcutLeftTwoThirds,
            DefaultsKey.windowLayoutShortcutRightTwoThirds,
            DefaultsKey.windowLayoutShortcutNextDisplay,
        ]

        let unassignedLayoutShortcutKeys = [
            DefaultsKey.windowLayoutShortcutTopLeftSixth,
            DefaultsKey.windowLayoutShortcutTopCenterSixth,
            DefaultsKey.windowLayoutShortcutTopRightSixth,
            DefaultsKey.windowLayoutShortcutBottomLeftSixth,
            DefaultsKey.windowLayoutShortcutBottomCenterSixth,
            DefaultsKey.windowLayoutShortcutBottomRightSixth,
            DefaultsKey.windowLayoutShortcutPreviousDisplay,
            DefaultsKey.windowLayoutShortcutMarginMaximize,
        ]

        var coldCacheCaps: [String] = []

        let coldCacheDone = DispatchSemaphore(value: 0)

        // Every assertion above compares labels the live input source produced,
        // so on a Latin-layout Mac they all pass whichever source the keycaps
        // are read from, and the one thing that made them wrong is invisible:
        // an input method answers the current-layout call with the layout it
        // types through, not the one printed on the keys. Pinned on the public
        // symbols rather than on the private member holding them, so renaming
        // it stays green and dropping the ASCII-capable lookup goes red.
        let shortcutSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Core/GlobalShortcut.swift",
            encoding: .utf8)) ?? ""

        let shortcutCode = shortcutSource.split(separator: "\n", omittingEmptySubsequences: false)
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .joined(separator: "\n")

        expect(shortcutCode.contains("TISCopyCurrentASCIICapableKeyboardLayoutInputSource")
                && shortcutCode.contains("TISCopyCurrentKeyboardInputSource")
                && shortcutCode.contains("kTISPropertyInputSourceType"),
               "keycaps come from the ASCII-capable layout while an input method is active")

        for language in AppLanguage.allCases {
            let layoutStrings = FeatureStrings.windowLayout(language)
            expect(!layoutStrings.fullScreen.isEmpty && !layoutStrings.previousDisplay.isEmpty
                    && !layoutStrings.marginMaximize.isEmpty
                    && !layoutStrings.centerHalf.isEmpty,
                   "\(language.rawValue) names the latest window layout actions")
        }

        print("[generated-checks] ThePanelSurfaceReachesThePopoverArrowIssue1030 \(checks)")
    }
}
