// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedLaunchAtLoginReconciliationTests: XCTestCase {
    func testLaunchAtLoginReconciliation() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        expect(LaunchAtLoginSupport.startupAction(wanted: true, registration: .off,
                                                  locationIsUnstable: false) == .register,
               "a lost registration the user wants is redone at startup")

        expect(LaunchAtLoginSupport.startupAction(wanted: true, registration: .off,
                                                  locationIsUnstable: true) == .none,
               "no registration is redone from an unstable location")

        expect(LaunchAtLoginSupport.startupAction(wanted: true, registration: .enabled,
                                                  locationIsUnstable: false) == .none
                && LaunchAtLoginSupport.startupAction(wanted: true, registration: .enabled,
                                                      locationIsUnstable: true) == .none,
               "a healthy registration is left alone")

        expect(LaunchAtLoginSupport.startupAction(wanted: false, registration: .enabled,
                                                  locationIsUnstable: false) == .adoptEnabled
                && LaunchAtLoginSupport.startupAction(wanted: false, registration: .enabled,
                                                      locationIsUnstable: true) == .adoptEnabled,
               "an enable made outside the app becomes the stored choice")

        expect(LaunchAtLoginSupport.startupAction(wanted: false, registration: .off,
                                                  locationIsUnstable: false) == .none
                && LaunchAtLoginSupport.startupAction(wanted: false, registration: .off,
                                                      locationIsUnstable: true) == .none,
               "startup never turns launch at login on for a user who never asked")

        expect(LaunchAtLoginSupport.startupAction(wanted: true, registration: .needsApproval,
                                                  locationIsUnstable: false) == .none
                && LaunchAtLoginSupport.startupAction(wanted: false, registration: .needsApproval,
                                                      locationIsUnstable: false) == .none,
               "an item awaiting approval in System Settings is never registered over (issue #260)")

        print("[generated-checks] LaunchAtLoginReconciliation \(checks)")
    }
}
