// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedHotCPUAlertTests: XCTestCase {
    func testHotCPUAlert() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        var spikeGate = SustainedAlertGate()

        expect(!spikeGate.shouldAlert(reading: 99, threshold: 90, readAt: 100),
               "a single hot reading is not a hot CPU yet")

        expect(!spikeGate.shouldAlert(reading: 99, threshold: 90, readAt: 108),
               "a second hot reading inside the window still waits")

        expect(spikeGate.shouldAlert(reading: 99, threshold: 90, readAt: 112),
               "a temperature that holds past the window alerts")

        var carriedGate = SustainedAlertGate()

        expect(!carriedGate.shouldAlert(reading: 101, threshold: 90, readAt: 200),
               "the reading behind a spike starts the window")

        var carriedAlerts = 0

        for _ in 0..<60 {
            if carriedGate.shouldAlert(reading: 101, threshold: 90, readAt: 200) {
                carriedAlerts += 1
            }
        }

        expect(carriedAlerts == 0,
               "the same reading served again never ages into an alert on its own")

        var coolingGate = SustainedAlertGate()

        _ = coolingGate.shouldAlert(reading: 99, threshold: 90, readAt: 300)

        expect(!coolingGate.shouldAlert(reading: 52, threshold: 90, readAt: 315),
               "a reading back under the limit does not alert")

        expect(!coolingGate.shouldAlert(reading: 99, threshold: 90, readAt: 330),
               "cooling down restarts the window instead of resuming the old one")

        expect(coolingGate.shouldAlert(reading: 99, threshold: 90, readAt: 345),
               "the restarted window alerts on its own merits")

        var quietGate = SustainedAlertGate()

        expect(!quietGate.shouldAlert(reading: 89, threshold: 90, readAt: 400),
               "a reading under the limit is not hot")

        expect(!quietGate.shouldAlert(reading: 89, threshold: 90, readAt: 500),
               "staying under the limit never alerts")

        expect(!quietGate.shouldAlert(reading: nil, threshold: 90, readAt: 600),
               "a missing temperature does not alert")

        expect(!quietGate.shouldAlert(reading: 99, threshold: 90, readAt: nil),
               "a temperature with no reading time does not alert")

        print("[generated-checks] HotCPUAlert \(checks)")
    }
}
