// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedDockPreviewHelpersTests: XCTestCase {
    func testDockPreviewHelpers() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let previousPreviewSize = UserDefaults.standard.object(forKey: DefaultsKey.previewSize)

        UserDefaults.standard.set("small", forKey: DefaultsKey.previewSize)

        UserDefaults.standard.set("xlarge", forKey: DefaultsKey.previewSize)

        if let previousPreviewSize {
            UserDefaults.standard.set(previousPreviewSize, forKey: DefaultsKey.previewSize)
        } else {
            UserDefaults.standard.removeObject(forKey: DefaultsKey.previewSize)
        }

        var bareActivationYields: [String] = []

        var scannedActivationFiles = 0

        var dockAccessibilityLookups = 0

        expect(MiddleClickSupport.actionForClick(fingerCount: 3, frameAge: 0.05, settledFor: 0.2,
                                                 sinceLastTransformEnd: nil,
                                                 systemDragGestureEnabled: false) == .transform,
               "middle click transforms a settled three-finger press")

        expect(MiddleClickSupport.actionForClick(fingerCount: 2, frameAge: 0.05, settledFor: 0.2,
                                                 sinceLastTransformEnd: nil,
                                                 systemDragGestureEnabled: false) == .passThrough,
               "middle click leaves two-finger clicks alone")

        expect(MiddleClickSupport.actionForClick(fingerCount: 4, frameAge: 0.05, settledFor: 0.2,
                                                 sinceLastTransformEnd: nil,
                                                 systemDragGestureEnabled: false) == .passThrough,
               "middle click leaves four-finger clicks alone")

        expect(MiddleClickSupport.actionForClick(fingerCount: 3, frameAge: 1.0, settledFor: 0.2,
                                                 sinceLastTransformEnd: nil,
                                                 systemDragGestureEnabled: false) == .passThrough,
               "middle click ignores stale contact frames (fingers already lifted)")

        expect(MiddleClickSupport.actionForClick(fingerCount: 3, frameAge: 0.05, settledFor: 0.01,
                                                 sinceLastTransformEnd: nil,
                                                 systemDragGestureEnabled: false) == .passThrough,
               "middle click rejects a click arriving with the third finger's touchdown")

        expect(MiddleClickSupport.actionForClick(fingerCount: 3, frameAge: 0.05, settledFor: 0.2,
                                                 sinceLastTransformEnd: 0.1,
                                                 systemDragGestureEnabled: false) == .swallow,
               "middle click drops the tap-to-click bounce right after a transform")

        expect(MiddleClickSupport.actionForClick(fingerCount: 3, frameAge: 0.05, settledFor: 0.2,
                                                 sinceLastTransformEnd: 0.5,
                                                 systemDragGestureEnabled: false) == .transform,
               "middle click accepts a deliberate second press after the guard window")

        expect(MiddleClickSupport.actionForClick(fingerCount: 1, frameAge: 0.05, settledFor: 0,
                                                 sinceLastTransformEnd: 0.1,
                                                 systemDragGestureEnabled: false) == .passThrough,
               "middle click never swallows ordinary one-finger clicks")

        expect(MiddleClickSupport.actionForClick(fingerCount: 3, frameAge: 0.05, settledFor: 0.2,
                                                 sinceLastTransformEnd: nil,
                                                 systemDragGestureEnabled: true) == .passThrough,
               "middle click stands down while the system three-finger drag owns the gesture")

        var minimizeIntentMinimizedReads = 0

        var minimizeIntentFocusedReads = 0

        func minimizeIntentMinimized(_ value: Bool) -> Bool {
            minimizeIntentMinimizedReads += 1
            return value
        }

        func minimizeIntentFocused(_ value: UInt32?) -> UInt32? {
            minimizeIntentFocusedReads += 1
            return value
        }

        // The shared take-over works on raw WindowServer ids. Same transition
        // rule as the switcher had: suppress only what is enabled now, restore
        // only what we own and no longer want.
        expect(SystemShortcutTakeoverSupport.transition(from: [], to: [1, 2, 30], currentlyEnabled: [1, 30])
               == SystemShortcutTransition(suppress: [1, 30], restore: [])
               && SystemShortcutTakeoverSupport.transition(from: [1, 30], to: [], currentlyEnabled: [])
               == SystemShortcutTransition(suppress: [], restore: [1, 30]),
               "the shared take-over suppresses only enabled ids and restores only owned ones")

        expect(SystemShortcutTakeoverSupport.migratedMarker(old: [27, 28], new: [30]) == [27, 28, 30]
               && SystemShortcutTakeoverSupport.migratedMarker(old: nil, new: nil).isEmpty
               && SystemShortcutTakeoverSupport.migratedMarker(old: [99_999_999_999], new: nil).isEmpty,
               "the old switcher marker folds into the shared one once, dropping anything that is not an id")

        // #1357's contracts, now carried by the shared rule. Launch gives back
        // every id the marker still holds, including when the App Switcher is
        // off: a feature that is off claims none of them, so all of them are
        // restored without the switcher's tap or the feature being installed.
        let legacyMarker = SystemShortcutTakeoverSupport.migratedMarker(old: [27, 28, 220], new: nil)

        expect(SystemShortcutTakeoverSupport.recoveryTransition(from: legacyMarker, keeping: [])
               == SystemShortcutTransition(suppress: [], restore: [27, 28, 220]),
               "launch gives back a marker left by an earlier build even with the switcher off")

        var recoveryWrites: [Int32] = []

        let recordRecoveryWrite: (Int32, Bool) -> Bool = { id, _ in
            recoveryWrites.append(id)
            return true
        }

        let cleanLaunchOwnership = SystemShortcutTakeoverSupport.apply(
            SystemShortcutTakeoverSupport.recoveryTransition(from: [], keeping: [1, 2, 27, 220]),
            owned: [], setEnabled: recordRecoveryWrite, persist: { _ in })

        expect(cleanLaunchOwnership.isEmpty && recoveryWrites.isEmpty,
               "clean launch leaves system shortcuts working until the replacement tap is live")

        let recoveredOwnership = SystemShortcutTakeoverSupport.apply(
            SystemShortcutTakeoverSupport.recoveryTransition(from: legacyMarker, keeping: [1, 27, 220]),
            owned: legacyMarker, setEnabled: recordRecoveryWrite, persist: { _ in })

        expect(recoveredOwnership == [27, 220] && recoveryWrites == [28],
               "crash recovery gives back stale keys without toggling retained keys or taking new ones")

        // Say the WindowServer refused 28: `apply` leaves it in the marker, so
        // every later transition asks for it again and the give-back finishes
        // at the next take-over or in the next process.
        expect(SystemShortcutTakeoverSupport.transition(from: [28], to: [1], currentlyEnabled: [1])
               == SystemShortcutTransition(suppress: [1], restore: [28]),
               "an id whose give-back failed stays owned and is retried while another key is taken over")

        expect(SystemShortcutTakeoverSupport.transition(from: [1, 28], to: [], currentlyEnabled: [])
               == SystemShortcutTransition(suppress: [], restore: [1, 28]),
               "a marker that survived a failed give-back is retried in full by the next process")

        expect(SystemShortcutTakeoverSupport.transition(from: [], to: [], currentlyEnabled: [1, 28])
               == SystemShortcutTransition(suppress: [], restore: []),
               "an id given back successfully leaves the marker and is never switched on again")

        // The pass itself, against a fake table: the marker must be on disk
        // before a key is switched off, a refused disable must take the key
        // back out, and a refused enable must leave it in for the retry.
        var fakeEnabled: Set<Int32> = [1, 27]

        var refused: Set<Int32> = []

        var markers: [Set<Int32>] = []

        var writeAheadMissing = false

        let fakeSetEnabled: (Int32, Bool) -> Bool = { id, on in
            if !on, !(markers.last?.contains(id) ?? false) { writeAheadMissing = true }
            guard !refused.contains(id) else { return false }
            if on { fakeEnabled.insert(id) } else { fakeEnabled.remove(id) }
            return true
        }

        let record: (Set<Int32>) -> Void = { markers.append($0) }

        refused = [27]

        let afterRefusedDisable = SystemShortcutTakeoverSupport.apply(
            SystemShortcutTransition(suppress: [1, 27], restore: []), owned: [],
            setEnabled: fakeSetEnabled, persist: record)

        expect(afterRefusedDisable == [1] && fakeEnabled == [27] && markers.last == [1]
               && markers.contains(where: { $0.contains(27) }),
               "a refused disable rolls the key back out of the marker it was written ahead into")

        refused = [1]

        let afterRefusedEnable = SystemShortcutTakeoverSupport.apply(
            SystemShortcutTransition(suppress: [], restore: [1]), owned: afterRefusedDisable,
            setEnabled: fakeSetEnabled, persist: record)

        expect(afterRefusedEnable == [1] && !fakeEnabled.contains(1),
               "a refused enable keeps the key in the marker for the next pass to retry")

        refused = []

        expect(SystemShortcutTakeoverSupport.apply(
                   SystemShortcutTransition(suppress: [], restore: [1]), owned: afterRefusedEnable,
                   setEnabled: fakeSetEnabled, persist: record).isEmpty && fakeEnabled == [1, 27],
               "the retry finishes the give-back")

        expect(!writeAheadMissing, "ownership is persisted before every disable")

        print("[generated-checks] DockPreviewHelpers \(checks)")
    }
}
