// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedScreenRecorderMotionTests: XCTestCase {
    func testScreenRecorderMotion() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let flatAlpha = RecorderMotion.onePoleAlpha(cutoff: 2, dt: 1.0 / 60)

        expect(abs(flatAlpha - 0.18899) < 0.0001,
               "the one-pole coefficient matches the closed form at 60 fps")

        expect(RecorderMotion.onePoleAlpha(cutoff: 0, dt: 1.0 / 60) == 1,
               "no smoothing at all passes the signal straight through")

        // A step is the hardest case: a causal filter lands late, a forward
        // and backward pass lands on time. That is the whole reason the
        // recording is finished before any of this runs.
        let step = (0..<120).map { $0 < 60 ? 0.0 : 1.0 }

        let filtered = RecorderMotion.filtfilt(step, alpha: 0.28)

        expect(filtered.count == step.count,
               "smoothing returns as many samples as it was given")

        expect(abs(filtered[59] - 0.5) < 0.2,
               "the smoothed step crosses halfway AT the step, not after it")

        expect(filtered[0] < 0.02 && filtered[119] > 0.98,
               "the padded ends are not dragged toward the middle of the clip")

        var monotonic = true

        for index in 1..<filtered.count where filtered[index] < filtered[index - 1] - 1e-9 {
            monotonic = false
        }

        expect(monotonic, "smoothing a step never overshoots or rings")

        let clicks = [RecorderMotion.Click(time: 1.0, isDown: true),
                      RecorderMotion.Click(time: 1.3, isDown: false)]

        expect(RecorderMotion.anchorWeight(at: 1.0, clicks: clicks) == 1,
               "at the moment of the press the pointer is exactly where it really was")

        expect(RecorderMotion.anchorWeight(at: 1.15, clicks: clicks) == 1,
               "through a drag the pointer tracks the truth, or what is dragged comes loose")

        expect(RecorderMotion.anchorWeight(at: 0.5, clicks: clicks) == 0,
               "far from a click the smoothed path is used as it is")

        expect(RecorderMotion.anchorWeight(at: 0.94, clicks: clicks) > 0
                && RecorderMotion.anchorWeight(at: 0.94, clicks: clicks) < 1,
               "the blend back to the truth eases in rather than snapping")

        let openDrag = [RecorderMotion.Click(time: 2.0, isDown: true)]

        expect(RecorderMotion.anchorWeight(at: 5.0, clicks: openDrag) == 1,
               "a recording that ended mid drag keeps tracking to the end")

        expect(RecorderMotion.smoothstep(0) == 0 && RecorderMotion.smoothstep(1) == 1
                && RecorderMotion.smoothstep(0.5) == 0.5,
               "the easing runs from nothing to everything through the middle")

        expect(RecorderMotion.smootherstep(-4) == 0 && RecorderMotion.smootherstep(9) == 1,
               "easing outside its range is clamped instead of exploding")

        print("[generated-checks] ScreenRecorderMotion \(checks)")
    }
}
