// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedMusicLaunchBlockerTests: XCTestCase {
    func testMusicLaunchBlocker() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        func musicKeyData(keyCode: Int, state: Int = 10, repeatFlag: Bool = false) -> Int {
            Int((UInt32(keyCode) << 16) | (UInt32(state) << 8) | (repeatFlag ? 1 : 0))
        }

        expect(MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: Int(MusicLaunchSupport.playPauseKeyCode))),
               "play/pause arms the music-app blocker")

        expect(MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: Int(MusicLaunchSupport.nextTrackKeyCode))),
               "next track arms the music-app blocker")

        expect(MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: Int(MusicLaunchSupport.previousTrackKeyCode))),
               "previous track arms the music-app blocker")

        expect(MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: Int(MusicLaunchSupport.fastForwardKeyCode))),
               "fast-forward arms the music-app blocker")

        expect(MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: Int(MusicLaunchSupport.rewindKeyCode))),
               "rewind arms the music-app blocker")

        expect(!MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: Int(MusicLaunchSupport.playPauseKeyCode), state: 11)),
               "a media-key release does not arm the blocker")

        expect(!MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: Int(MusicLaunchSupport.playPauseKeyCode), repeatFlag: true)),
               "auto-repeat does not re-arm the blocker")

        expect(!MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: 0)),
               "volume keys do not arm the blocker")

        expect(!MusicLaunchSupport.isMusicLaunchTrigger(
            subtype: MusicLaunchSupport.auxiliaryControlButtonsSubtype,
            data1: musicKeyData(keyCode: 2)),
               "brightness keys do not arm the blocker")

        expect(!MusicLaunchSupport.isMusicLaunchTrigger(subtype: 1, data1: musicKeyData(keyCode: 16)),
               "other system-defined subtypes do not arm the blocker")

        expect(!MusicLaunchSupport.shouldBlockLaunch(now: 10, lastTriggerAt: nil),
               "without a recent media key the music app may open")

        expect(MusicLaunchSupport.shouldBlockLaunch(now: 10, lastTriggerAt: 9.5),
               "a launch in the arm window after a media key is blocked")

        expect(MusicLaunchSupport.shouldBlockLaunch(now: 10, lastTriggerAt: 8.0),
               "a launch on the arm-window edge is still blocked")

        expect(!MusicLaunchSupport.shouldBlockLaunch(now: 10, lastTriggerAt: 7.9),
               "a launch after the arm window is left alone")

        print("[generated-checks] MusicLaunchBlocker \(checks)")
    }
}
