// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedScreenRecorderPicturesTests: XCTestCase {
    func testScreenRecorderPictures() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let mark = RecorderImageOverlay(path: "/tmp/logo.png", start: 2, end: 6)

        expect(mark.opacity(at: 1.9) == 0 && mark.opacity(at: 6.1) == 0,
               "a picture is not there before it starts or after it ends")

        expect(mark.opacity(at: 4) == 1,
               "a picture is at full strength in the middle of its own time")

        expect(mark.opacity(at: 2.1) > 0 && mark.opacity(at: 2.1) < 1,
               "a picture eases in like a caption instead of appearing on one frame")

        expectClose(RecorderImageOverlay(path: "/tmp/logo.png", start: 0, end: 10, opacity: 0.5)
                        .opacity(at: 5),
                    0.5,
                    "a picture never goes past the strength it was given")

        expect(RecorderImageOverlay(path: "   ", start: 1, end: 5).sanitized(duration: 10) == nil,
               "a picture with no file behind it is dropped rather than drawn")

        expect(RecorderImageOverlay(path: "/tmp/logo.png", start: 9, end: 30)
                .sanitized(duration: 10)?.end == 10,
               "a picture that runs past the recording is brought back inside it")

        expect(RecorderImageOverlay(path: "/tmp/logo.png", start: 5, end: 5.05)
                .sanitized(duration: 10) == nil,
               "a picture too brief to see is not kept")

        expect(RecorderImageOverlay(path: "/tmp/logo.png", start: 1, end: 5, size: 9)
                .sanitized(duration: 10)?.size == RecorderImageOverlay.sizeRange.upperBound,
               "an impossible picture size is clamped instead of filling the frame")

        expect(RecorderImageOverlay(path: "/tmp/logo.png", start: 1, end: 5, opacity: 0)
                .sanitized(duration: 10)?.opacity == RecorderImageOverlay.opacityRange.lowerBound,
               "a picture turned invisible keeps the least strength that can still be seen")

        expect(RecorderImageOverlay(path: "relative.png", start: 0, end: 2)
                .sanitized(duration: 3) == nil,
               "a damaged picture path never resolves against the app's working directory")

        expect(RecorderImageOverlay(path: "/tmp/picture.png ", start: 0, end: 2)
                .sanitized(duration: 3)?.path == "/tmp/picture.png ",
               "a picked filename keeps its actual whitespace")

        let pictureRoot = FileManager.default.temporaryDirectory
            .appendingPathComponent("recorder-image-test-" + UUID().uuidString, isDirectory: true)

        print("[generated-checks] ScreenRecorderPictures \(checks)")
    }
}
