// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedWattsPercentTests: XCTestCase {
    func testWattsPercent() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        // Carried over: state an earlier section of MetricsTests.swift set and this one inherits.
        MetricFormat.locale = Locale(identifier: "en_US_POSIX")

        expectEqual(MetricFormat.watts(8.5), "8.5 W", "watts under 10")

        expectEqual(MetricFormat.watts(23.4), "23 W", "watts over 10 rounds")

        expectEqual(MetricFormat.wattsCompact(8.6), "9W", "watts compact rounds")

        expectEqual(MetricFormat.percent(0), "0%", "percent 0")

        expectEqual(MetricFormat.percent(0.125), "13%", "percent rounds")

        expectEqual(MetricFormat.percent(1), "100%", "percent full")

        expectEqual(MetricFormat.percent(1.4), "100%", "percent clamps high")

        expectEqual(MetricFormat.percent(-0.2), "0%", "percent clamps low")

        expectClose(MetricFormat.boundedPercentage(130), 100,
                    "process percentage clamps above full hardware utilization")

        expectClose(MetricFormat.boundedPercentage(-5), 0,
                    "process percentage clamps negative utilization")

        expect(MetricFormat.machTimeNanoseconds(48_000_000,
                                                numerator: 125,
                                                denominator: 3) == 2_000_000_000,
               "libproc CPU ticks convert through the platform Mach timebase")

        expectClose(MetricFormat.processCPUPercentage(previousNanoseconds: 1_000_000_000,
                                                       currentNanoseconds: 2_800_000_000,
                                                       elapsed: 2,
                                                       processorCount: 18), 5,
                    "process CPU delta uses the monitor wall-clock interval and machine capacity")

        expectClose(MetricFormat.processCPUPercentage(previousNanoseconds: 2_000_000_000,
                                                       currentNanoseconds: 1_000_000_000,
                                                       elapsed: 2,
                                                       processorCount: 18), 0,
                    "process CPU counter resets do not create utilization spikes")

        expectClose(MetricFormat.processReconciliationScale(sampledTotal: 12,
                                                             aggregatePercentage: 7), 7.0 / 12.0,
                    "process usage scales down when attribution exceeds the aggregate")

        expectClose(MetricFormat.processReconciliationScale(sampledTotal: 5,
                                                             aggregatePercentage: 7), 1,
                    "unattributed aggregate usage does not inflate process rows")

        expectEqual(MetricFormat.menuBarMemoryPercent(used: 79, total: 100), "79%",
                    "menu bar memory shows the current RAM percentage")

        expectEqual(MetricFormat.menuBarMemoryPercent(used: nil, total: 100), "--%",
                    "menu bar memory keeps a placeholder when used RAM is unavailable")

        expectEqual(MetricFormat.menuBarMemoryPercent(used: 79, total: nil), "--%",
                    "menu bar memory keeps a placeholder when total RAM is unavailable")

        expectEqual(MetricFormat.menuBarMemoryPercent(used: 79, total: 0), "--%",
                    "menu bar memory keeps a placeholder when total RAM is invalid")

        expectClose(MetricFormat.stabilizedGPUUsage(previous: 0.03, current: 0.80), 0.23,
                    "GPU usage readout caps one-tick upward spikes")

        expectClose(MetricFormat.stabilizedGPUUsage(previous: 0.23, current: 0.80), 0.43,
                    "GPU usage readout still climbs during sustained load")

        expectClose(MetricFormat.stabilizedGPUUsage(previous: 0.60, current: 0.10), 0.275,
                    "GPU usage readout falls quickly after transient load")

        expectClose(MetricFormat.stabilizedGPUUsage(previous: nil, current: 1.4), 1.0,
                    "GPU usage readout clamps first sample")

        expectEqual(MetricFormat.temperature(0, unit: .celsius), "0 °C", "celsius freezing")

        expectEqual(MetricFormat.temperature(0, unit: .fahrenheit), "32 °F", "fahrenheit freezing")

        expectEqual(MetricFormat.temperature(41, unit: .fahrenheit), "106 °F", "fahrenheit rounds")

        expectEqual(MetricFormat.temperatureCompact(49.6, unit: .celsius), "50°", "compact celsius rounds")

        expectEqual(MetricFormat.temperatureCompact(49.6, unit: .fahrenheit), "121°", "compact fahrenheit rounds")

        expectEqual(MetricFormat.temperatureUnitSuffix(.celsius), "°C", "celsius suffix is explicit")

        expectEqual(MetricFormat.temperatureUnitSuffix(.fahrenheit), "°F", "fahrenheit suffix is explicit")

        print("[generated-checks] WattsPercent \(checks)")
    }
}
