// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedCommandBarWhatThePersonControlsTests: XCTestCase {
    func testCommandBarWhatThePersonControls() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        expect(CommandBarSource.allCases.map(\.rawValue) == [
            "actions", "apps", "menus", "windows", "quitApps", "settingsPages", "macSettings",
            "snippets", "clipboard", "emoji", "folders", "answers", "calculator",
            "selection", "links", "files", "killProcess",
        ], "source ids are stable (they persist inside the disabled list)")

        expect(CommandBarSource.actions.isAlwaysOn
                && CommandBarSource.allCases.filter(\.isAlwaysOn).count == 1,
               "only the app's own actions cannot be switched off")

        expect(CommandBarClipboardAccess.canUseHistory(captureEnabled: true,
                                                       hasSavedItems: false),
               "clipboard capture makes the command bar history available")

        expect(CommandBarClipboardAccess.canUseHistory(captureEnabled: false,
                                                       hasSavedItems: true),
               "saved clipboard items stay available when capture is off")

        expect(!CommandBarClipboardAccess.canUseHistory(captureEnabled: false,
                                                        hasSavedItems: false),
               "an empty disabled clipboard still points to setup")

        let japaneseClipboard = FeatureStrings.clipboard(.ja)

        let clipboardClearKeywords = [japaneseClipboard.title,
                                      ClipboardFeatureStrings.enUS.title,
                                      ClipboardFeatureStrings.enUS.clearRecent]
            .joined(separator: " ")

        expect(CommandBarSearch.matches(title: japaneseClipboard.clearRecent,
                                        keywords: clipboardClearKeywords,
                                        query: "clear clipboard"),
               "the clipboard clear action stays findable by its English name in a non-Latin locale")

        print("[generated-checks] CommandBarWhatThePersonControls \(checks)")
    }
}
