// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedByteRateFormattingTests: XCTestCase {
    func testByteRateFormatting() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        // Pinned, because everything below reads a decimal point and this
        // machine's region is only one of the ones the app ships for.
        MetricFormat.locale = Locale(identifier: "en_US_POSIX")

        expectEqual(MetricFormat.bytes(0), "0 B", "bytes zero")

        expectEqual(MetricFormat.bytes(512), "512 B", "bytes < 1K")

        expectEqual(MetricFormat.bytes(1024), "1.0 KB", "bytes 1K")

        expectEqual(MetricFormat.bytes(1536), "1.5 KB", "bytes 1.5K")

        // Seven of the thirteen languages here are spoken where a decimal is
        // written with a comma, and the panel wrote a point at everyone.
        MetricFormat.locale = Locale(identifier: "pt_BR")

        expectEqual(MetricFormat.bytes(1536), "1,5 KB", "a comma region reads its own decimal")

        expectEqual(MetricFormat.temperature(21.4, unit: .celsius), "21 °C",
                    "a whole number is untouched by the region")

        MetricFormat.locale = Locale(identifier: "en_US_POSIX")

        expectEqual(MetricFormat.bytes(10 * 1024), "10 KB", "bytes 10K drops decimal")

        expectEqual(MetricFormat.bytes(1024 * 1024), "1.0 MB", "bytes 1M")

        expectEqual(MetricFormat.bytes(3 * 1024 * 1024 * 1024), "3.0 GB", "bytes 3G")

        expectEqual(MetricFormat.diskBytes(245_107_195_904), "245 GB", "disk bytes use decimal storage units")

        expectEqual(MetricFormat.diskBytes(1_000_204_845_056), "1.0 TB", "disk bytes show decimal terabytes")

        expectEqual(MetricFormat.diskBytes(123_456_789_000), "123 GB", "disk bytes match Finder-style GB")

        expectEqual(MetricFormat.diskBytesPrecise(14_878_047_232_000), "14.88 TB",
                    "precise disk bytes keep SMART totals readable")

        expectEqual(MetricFormat.bytesPerSec(0), "0 B/s", "rate zero")

        expectEqual(MetricFormat.bytesPerSec(2 * 1024 * 1024), "2.0 MB/s", "rate 2M")

        expectEqual(MetricFormat.bytesPerSec(1500 * 1024), "1.5 MB/s", "rate 1.5M")

        expectEqual(MetricFormat.bytesPerSecCompact(0), "0B", "compact zero")

        expectEqual(MetricFormat.bytesPerSecCompact(320 * 1024), "320K", "compact 320K")

        expectEqual(MetricFormat.bytesPerSecCompact(1.2 * 1024 * 1024), "1.2M", "compact 1.2M")

        expectEqual(MetricFormat.bytesPerSecCompact(1022), "1022B", "compact 1022B remains stable")

        expectEqual(MetricFormat.bytesPerSecCompact(1023.4), "1023B", "compact keeps sub-kilobyte values")

        expectEqual(MetricFormat.bytesPerSecCompact(1023.6), "1.0K", "compact promotes rounded kilobyte edge")

        expectEqual(MetricFormat.bytesPerSecCompact(9.96 * 1024), "10K", "compact drops redundant decimal at 10K")

        expectEqual(MetricFormat.bytesPerSecCompact(1023.6 * 1024), "1.0M", "compact promotes rounded megabyte edge")

        expectEqual(MetricFormat.bytesPerSecCompact(9.96 * 1024 * 1024), "10M", "compact drops redundant decimal at 10M")

        print("[generated-checks] ByteRateFormatting \(checks)")
    }
}
