// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedUninstallationPathsStayAlignedAcrossSelfUninstallAndToolsUninstallShTests: XCTestCase {
    func testUninstallationPathsStayAlignedAcrossSelfUninstallAndToolsUninstallSh() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let selfUninstallSource = (try? String(contentsOfFile: "Sources/Vorssaint/Services/SelfUninstall.swift",
                                              encoding: .utf8)) ?? ""

        let uninstallScriptSource = (try? String(contentsOfFile: "Tools/uninstall.sh",
                                                encoding: .utf8)) ?? ""

        expect(!selfUninstallSource.isEmpty && !uninstallScriptSource.isEmpty,
               "uninstall sources read back for uninstallation alignment check")

        let queryHabitSupportSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/CommandBar/CommandBarSupport.swift",
            encoding: .utf8)) ?? ""

        expect(selfUninstallSource.contains("CommandBarQueryHabits.removeInstallationKey()")
                && queryHabitSupportSource.contains("installationKeyCache.stopAndRemove {")
                && queryHabitSupportSource.contains("SecItemDelete([")
                && queryHabitSupportSource.contains("kSecClass: kSecClassGenericPassword")
                && queryHabitSupportSource.contains("kSecAttrService: keyService")
                && queryHabitSupportSource.contains("kSecAttrAccount: keyAccount")
                && queryHabitSupportSource.contains("keyService = installationKeyService(")
                && queryHabitSupportSource.contains("keyAccount = \"hmac-key\"")
                && uninstallScriptSource.contains("/usr/bin/security delete-generic-password")
                && uninstallScriptSource.contains("-s \"$BUNDLE.command-bar-query-habits\" -a \"hmac-key\""),
               "both uninstall paths remove only the query-learning Keychain item")

        let requiredSubpaths = ["Library/Application Support", "Library/Caches", "Library/HTTPStorages"]

        for subpath in requiredSubpaths {
            expect(selfUninstallSource.contains(subpath) && uninstallScriptSource.contains(subpath),
                   "both in-app and script uninstall sweep \(subpath)")
        }

        expect(uninstallScriptSource.contains("Library/Preferences/ByHost"),
               "script uninstall sweeps ByHost preferences")

        // Restoring sleep used to be fired and forgotten at both exits. A
        // failure there leaves `pmset disablesleep 1` set system-wide, and
        // removal deletes the flag that launch-time recovery reads before it
        // reads the setting, so nothing repairs it afterwards — a reinstall
        // included.
        let uninstallerSource = (try? String(contentsOfFile: "Sources/Vorssaint/Support/Uninstaller.swift",
                                             encoding: .utf8)) ?? ""

        expect(!uninstallerSource.isEmpty,
               "uninstaller entry point reads back for the sleep restore check")

        expect(!selfUninstallSource.contains("_ = Sudoers.pmsetDisableSleep")
                && !uninstallerSource.contains("_ = Sudoers.pmsetDisableSleep"),
               "neither uninstall path discards the result of restoring sleep")

        expect(selfUninstallSource.contains("guard detachFromSystem() else")
                && selfUninstallSource.contains("restoreSleepBeforeRemoval() -> Bool")
                && selfUninstallSource.contains("guard FanControlService.restoreAndUnregisterForRemoval() else")
                && selfUninstallSource.contains("adminPromptRecover")
                && selfUninstallSource.contains("verification.status == 0"),
               "in-app uninstall aborts unless fans and normal sleep are restored before removal")

        expect(uninstallScriptSource.contains("SleepDisabled"),
               "script uninstall reads the sleep setting back for itself")

        print("[generated-checks] UninstallationPathsStayAlignedAcrossSelfUninstallAndToolsUninstallSh \(checks)")
    }
}
