// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedCleaningModeUnlockGestureTests: XCTestCase {
    func testCleaningModeUnlockGesture() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let escapeKeyCode: Int64 = 53

        // Five deliberate Escape taps unlock, on the fifth.
        var taps = CleaningUnlockCounter(requiredKeyCode: escapeKeyCode, threshold: 5, pressWindow: 2.0)

        var tapUnlock = false

        for (i, t) in [0.0, 0.3, 0.6, 0.9, 1.2].enumerated() {
            tapUnlock = taps.registerKeyDown(code: escapeKeyCode, time: t, isRepeat: false)
            if i < 4 { expect(!tapUnlock, "no unlock before the fifth tap (\(i + 1))") }
        }

        expect(tapUnlock, "five Escape taps unlock")

        expect(taps.progress == 5, "progress reaches the threshold")

        // Wiping other keys cannot make progress toward unlock.
        var wipe = CleaningUnlockCounter(requiredKeyCode: escapeKeyCode, threshold: 5, pressWindow: 2.0)

        var wipeUnlock = false

        for (i, code) in [Int64(10), 11, 12, 13, 14, 15, 16, 17].enumerated() {
            if wipe.registerKeyDown(code: code, time: Double(i) * 0.1, isRepeat: false) { wipeUnlock = true }
        }

        expect(!wipeUnlock, "wiping other keys never unlocks")

        expect(wipe.progress == 0, "other keys make no unlock progress")

        // A different key mid-streak resets the count completely.
        var streak = CleaningUnlockCounter(requiredKeyCode: escapeKeyCode, threshold: 5, pressWindow: 2.0)

        _ = streak.registerKeyDown(code: escapeKeyCode, time: 0.0, isRepeat: false)

        _ = streak.registerKeyDown(code: escapeKeyCode, time: 0.2, isRepeat: false)

        _ = streak.registerKeyDown(code: escapeKeyCode, time: 0.4, isRepeat: false)

        _ = streak.registerKeyDown(code: 8, time: 0.6, isRepeat: false)

        expect(streak.progress == 0, "a different key mid-streak clears progress")

        // Auto-repeat (holding Escape) is ignored, so resting on it can't unlock.
        var held = CleaningUnlockCounter(requiredKeyCode: escapeKeyCode, threshold: 5, pressWindow: 2.0)

        var heldUnlock = false

        for i in 0..<10 {
            if held.registerKeyDown(code: escapeKeyCode, time: Double(i) * 0.1, isRepeat: true) { heldUnlock = true }
        }

        expect(!heldUnlock, "auto-repeat never unlocks")

        expect(held.progress == 0, "auto-repeat does not advance progress")

        // A pause longer than the window restarts the count.
        var paused = CleaningUnlockCounter(requiredKeyCode: escapeKeyCode, threshold: 5, pressWindow: 2.0)

        _ = paused.registerKeyDown(code: escapeKeyCode, time: 0.0, isRepeat: false)

        _ = paused.registerKeyDown(code: escapeKeyCode, time: 0.5, isRepeat: false)

        expect(paused.progress == 2, "presses within the window accumulate")

        _ = paused.registerKeyDown(code: escapeKeyCode, time: 10.0, isRepeat: false)

        expect(paused.progress == 1, "a pause beyond the window restarts the count")

        // reset() clears everything.
        var cleared = CleaningUnlockCounter(requiredKeyCode: escapeKeyCode, threshold: 5, pressWindow: 2.0)

        _ = cleared.registerKeyDown(code: escapeKeyCode, time: 0.0, isRepeat: false)

        _ = cleared.registerKeyDown(code: escapeKeyCode, time: 0.2, isRepeat: false)

        expect(cleared.progress == 2, "progress accumulates before reset")

        cleared.reset()

        expect(cleared.progress == 0, "reset clears progress")

        let afterReset2 = cleared.registerKeyDown(code: escapeKeyCode, time: 0.4, isRepeat: false)

        expect(!afterReset2 && cleared.progress == 1, "after reset Escape starts fresh at 1")

        // Modifiers are the keys nearest Escape, so a cloth reaches them first.
        // They arrive as flags-changed events, which the tap feeds here too, and
        // one physical press reports twice — once down, once up. Both are resets.
        var smeared = CleaningUnlockCounter(requiredKeyCode: escapeKeyCode, threshold: 5, pressWindow: 6.0)

        let leftShiftKeyCode: Int64 = 56

        var smearedUnlock = false

        for t in [0.0, 0.5, 1.0, 1.5] {
            if smeared.registerKeyDown(code: escapeKeyCode, time: t, isRepeat: false) { smearedUnlock = true }
        }

        expect(smeared.progress == 4, "four Escapes stop one short of the threshold")

        _ = smeared.registerKeyDown(code: leftShiftKeyCode, time: 2.0, isRepeat: false)

        expect(smeared.progress == 0, "a modifier going down clears the Escape count")

        _ = smeared.registerKeyDown(code: leftShiftKeyCode, time: 2.1, isRepeat: false)

        expect(smeared.progress == 0, "the modifier's release resets again, idempotently")

        if smeared.registerKeyDown(code: escapeKeyCode, time: 2.5, isRepeat: false) { smearedUnlock = true }

        expect(!smearedUnlock && smeared.progress == 1,
               "four Escapes with a modifier in between never unlock; the next Escape starts at 1")

        var modifiersReachCounter = false

        var leakedEvents: [String] = []

        var failOpenReturns = 0

        func systemKeyData(keyCode: Int, state: Int, repeatFlag: Bool = false) -> Int {
            Int((UInt32(keyCode) << 16) | (UInt32(state) << 8) | (repeatFlag ? 1 : 0))
        }

        let brightnessDown = CleaningSystemKeyEvent.decode(
            subtype: CleaningSystemKeyEvent.auxiliaryControlButtonsSubtype,
            data1: systemKeyData(keyCode: 3, state: CleaningSystemKeyEvent.keyDownState)
        )

        expect(brightnessDown?.isKeyDown == true && brightnessDown?.isRepeat == false,
               "brightness key down is decoded from system-defined events")

        let volumeUpRepeat = CleaningSystemKeyEvent.decode(
            subtype: CleaningSystemKeyEvent.auxiliaryControlButtonsSubtype,
            data1: systemKeyData(keyCode: 0, state: CleaningSystemKeyEvent.keyDownState, repeatFlag: true)
        )

        expect(volumeUpRepeat?.isKeyDown == true && volumeUpRepeat?.isRepeat == true,
               "system-defined auto-repeat is preserved")

        let mediaNextUp = CleaningSystemKeyEvent.decode(
            subtype: CleaningSystemKeyEvent.auxiliaryControlButtonsSubtype,
            data1: systemKeyData(keyCode: 17, state: CleaningSystemKeyEvent.keyUpState)
        )

        expect(mediaNextUp?.isKeyDown == false,
               "system-defined key up is decoded without advancing unlock")

        let powerKey = CleaningSystemKeyEvent.decode(
            subtype: CleaningSystemKeyEvent.powerKeySubtype,
            data1: 0
        )

        expect(powerKey?.isKeyDown == true && powerKey?.isRepeat == false,
               "power and lock key system events are recognized")

        let unrelatedSystemEvent = CleaningSystemKeyEvent.decode(subtype: 99, data1: 0)

        expect(unrelatedSystemEvent == nil, "unrelated system-defined events do not count as unlock keys")

        print("[generated-checks] CleaningModeUnlockGesture \(checks)")
    }
}
