// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedInterfaceFilteringTests: XCTestCase {
    func testInterfaceFiltering() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        // Carried over: state an earlier section of MetricsTests.swift set and this one inherits.
        MetricFormat.locale = Locale(identifier: "en_US_POSIX")

        expect(MetricFormat.includeNetworkInterface("en0"), "en0 included")

        expect(MetricFormat.includeNetworkInterface("en12"), "en12 included")

        expect(!MetricFormat.includeNetworkInterface("lo0"), "lo0 excluded")

        expect(!MetricFormat.includeNetworkInterface("awdl0"), "awdl0 excluded")

        expect(!MetricFormat.includeNetworkInterface("nan0"), "nan0 excluded")

        expect(!MetricFormat.includeNetworkInterface("utun3"), "utun3 (VPN) excluded")

        expect(!MetricFormat.includeNetworkInterface("bridge0"), "bridge0 excluded")

        expect(!MetricFormat.includeNetworkInterface(""), "empty excluded")

        print("[generated-checks] InterfaceFiltering \(checks)")
    }
}
