// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedMediaSizeTargetsTests: XCTestCase {
    func testMediaSizeTargets() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let sizeTargetStrings: [(String, Strings)] = [
            ("en-US", .enUS), ("pt-BR", .ptBR), ("tr", .tr), ("ru", .ru), ("es", .es),
            ("de", .de), ("fr", .fr), ("it", .it), ("ja", .ja), ("ko", .ko),
            ("zh-Hans", .zhHans), ("zh-HK", .zhHK), ("zh-TW", .zhTW),
        ]

        for (name, strings) in sizeTargetStrings {
            expect(!strings.mediaSizingResolution.isEmpty
                    && !strings.mediaSizingFileSize.isEmpty
                    && !strings.mediaTargetSize.isEmpty
                    && !strings.mediaTargetSizeHint.isEmpty
                    && !strings.mediaErrorTargetTooSmall.isEmpty
                    && !strings.mediaMegabytesSuffix.isEmpty,
                   "\(name) names the size target controls")
        }

        // This run ends in exit(), which skips every defer, so scratch built
        // in the temp area is listed here and handed back before it reports.
        // The three defers that used to do it never ran once: a directory per
        // run had been piling up in the system's temp area for as long as the
        // suite has existed.
        var scratchPaths: [URL] = []

        let uniqueDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("vorssaint-media-unique-\(UUID().uuidString)", isDirectory: true)

        try? FileManager.default.createDirectory(at: uniqueDir, withIntermediateDirectories: true)

        scratchPaths.append(uniqueDir)

        let longBaseName = String(repeating: "😀", count: 100)

        for language in AppLanguage.allCases {
            let strings = MediaImageConverterStrings.localized(language)
            let values = Mirror(reflecting: strings).children.compactMap { $0.value as? String }
            expect(values.count == 56 && values.allSatisfy { !$0.isEmpty },
                   "every image converter string is set for \(language.rawValue)")
            expect(values.allSatisfy { !$0.contains("—") },
                   "no em-dash in visible image converter strings (\(language.rawValue))")
            expect(strings.filesSelectedFormat.contains("%d")
                   && strings.profileDefaultNameFormat.contains("%d")
                   && strings.savedBytesFormat.contains("%@")
                   && strings.grewBytesFormat.contains("%@")
                   && strings.batchSavedFormat.contains("%d")
                   && strings.batchPartialFormat.filter { $0 == "%" }.count == 2
                   && strings.batchSummaryHeaderFormat.filter { $0 == "%" }.count == 2
                   && strings.batchSummaryItemFormat.filter { $0 == "%" }.count == 2,
                   "image converter formats keep their arguments in \(language.rawValue)")
        }

        let mediaInput = URL(fileURLWithPath: "/tmp/Clip.mov")

        let hiddenMediaInput = URL(fileURLWithPath: "/tmp/.Clip.mov")

        let extensionOnlyMediaInput = URL(fileURLWithPath: "/tmp/.mov")

        let emptyBaseMediaInput = URL(fileURLWithPath: "/tmp/...")

        let mediaVisibilityDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("vorssaint-media-visibility-\(UUID().uuidString)", isDirectory: true)

        try? FileManager.default.createDirectory(at: mediaVisibilityDir,
                                                 withIntermediateDirectories: true)

        scratchPaths.append(mediaVisibilityDir)

        let visibleMediaOutput = mediaVisibilityDir.appendingPathComponent("Visible.gif")

        FileManager.default.createFile(atPath: visibleMediaOutput.path,
                                       contents: Data([0x47, 0x49, 0x46, 0x38]),
                                       attributes: nil)

        let intentionallyHiddenMediaOutput = mediaVisibilityDir.appendingPathComponent(".Manual.gif")

        FileManager.default.createFile(atPath: intentionallyHiddenMediaOutput.path,
                                       contents: Data([0x47, 0x49, 0x46, 0x38]),
                                       attributes: nil)

        var percentFieldAttached = false

        let headphonesSuite = "vorss.tests.mixer.headphones"

        let savedMixerVolumes = ["com.apple.Safari": 0.35, "com.apple.Music": 1.4]

        // The wedged tap that verdict tears down is also the one whose
        // `AudioHardwareDestroyProcessTap` parks inside the HAL. Serialized,
        // that one parked call held every later engine's aggregate and tap
        // alive behind it; unbounded, each one strands a worker of the shared
        // pool, which is issue #971's exhaustion. Read as source text because
        // the engine lives in a file the test target does not compile.
        let mixerCode = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/Audio/AppVolumeMixer.swift",
            encoding: .utf8)) ?? ""

        let teardownQueueSetup = mixerCode.range(of: "let teardownQueue").flatMap { start in
            mixerCode.range(of: "}()", range: start.upperBound..<mixerCode.endIndex)
                .map { String(mixerCode[start.upperBound..<$0.lowerBound]) }
        } ?? ""

        expect(teardownQueueSetup.contains("maxConcurrentOperationCount"),
               "engine teardown runs on a queue with a concurrency bound, not one thread and not one per engine")

        // The IO callback's two exits, read the same way: a cycle that never
        // found its tap must hand the device silence rather than what the HAL
        // left in the buffer (issue #326), and must leave without counting
        // itself alive — a callback that resolved no tap has done nothing for
        // the app that a callback which never ran would not have done, and
        // `tapChannels` is read once when the engine is built, so input that
        // never carried that shape never will. Ordering alone would not say
        // that: a count inside the missed-tap branch also reads as "after the
        // lookup". The branch is cut out by brace matching and the two halves
        // are checked apart.
        let mixerBody = mixerCode
            .components(separatedBy: "\n")
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .joined(separator: "\n")

        let missedTapBrace = mixerBody
            .range(of: "MixerRender.tapBufferIndex(in: inputBuffers")
            .flatMap { mixerBody.range(of: "else {", range: $0.upperBound..<mixerBody.endIndex) }

        var missedTapBranch = ""

        var afterMissedTap = ""

        if let missedTapBrace {
            var depth = 1
            var index = missedTapBrace.upperBound
            while index < mixerBody.endIndex, depth > 0 {
                if mixerBody[index] == "{" { depth += 1 }
                if mixerBody[index] == "}" { depth -= 1 }
                index = mixerBody.index(after: index)
            }
            if depth == 0 {
                missedTapBranch = String(mixerBody[missedTapBrace.upperBound..<mixerBody.index(before: index)])
                afterMissedTap = String(mixerBody[index...])
            }
        }

        expect(missedTapBranch.contains("MixerRender.silence(outputBuffers)")
               && missedTapBranch.contains("return"),
               "a callback that finds no tap silences the output before it leaves")

        expect(!missedTapBranch.isEmpty && !missedTapBranch.contains("cycles.increment()"),
               "a callback that finds no tap leaves without counting a cycle")

        let framesGuard = afterMissedTap.range(of: "guard frames > 0 else")?.upperBound

        let cycleCount = afterMissedTap.range(of: "cycles.increment()")?.lowerBound

        expect(framesGuard != nil && cycleCount != nil && framesGuard! < cycleCount!,
               "a cycle is counted only once the engine has handed the device audio")

        print("[generated-checks] MediaSizeTargets \(checks)")
    }
}
