// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedRemappableScreenshotToolShortcutsTests: XCTestCase {
    func testRemappableScreenshotToolShortcuts() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        var loupeAimFailure: String?

        expect(ScreenshotShareDuration.allCases.map(\.rawValue) == [3_600, 21_600, 86_400],
               "temporary links allow only one, six or twenty-four hours")

        let testShareEndpoint = ScreenshotSharingSupport.endpoint(
            bundleIdentifier: ScreenshotSharingSupport.developerBundleIdentifier,
            developerOverride: "https://test.example/")

        expect(testShareEndpoint.absoluteString == "https://test.example"
                && ScreenshotSharingSupport.endpoint(
                    bundleIdentifier: "com.vorssaint.utils",
                    developerOverride: "https://test.example").absoluteString
                    == ScreenshotSharingSupport.productionEndpoint.absoluteString
                && ScreenshotSharingSupport.endpoint(
                    bundleIdentifier: ScreenshotSharingSupport.developerBundleIdentifier,
                    developerOverride: "http://test.example")
                    == ScreenshotSharingSupport.productionEndpoint,
               "only the Developer build accepts a valid HTTPS test endpoint")

        expect(ScreenshotSharingSupport.uploadURL(endpoint: testShareEndpoint,
                                                  duration: .sixHours)?.absoluteString
                == "https://test.example/v1/screenshots?expiresIn=21600",
               "sharing builds the fixed upload route and expiration query")

        let shareNow = Date(timeIntervalSince1970: 1_000)

        let shareResponse = ScreenshotShareResponse(
            id: String(repeating: "a", count: 32),
            viewPath: "/s/\(String(repeating: "a", count: 32))",
            expiresAt: "1970-01-01T01:16:40.125Z",
            deleteToken: String(repeating: "b", count: 43))

        expect(ScreenshotSharingSupport.record(response: shareResponse,
                                                endpoint: testShareEndpoint,
                                                now: shareNow)?.url.absoluteString
                == "https://test.example/s/\(String(repeating: "a", count: 32))",
               "a valid service response becomes an owner-held link record")

        let forgedShareResponse = ScreenshotShareResponse(
            id: "guessable",
            viewPath: "/s/guessable",
            expiresAt: "1970-01-01T01:16:40.125Z",
            deleteToken: "short")

        expect(ScreenshotSharingSupport.record(response: forgedShareResponse,
                                                endpoint: testShareEndpoint,
                                                now: shareNow) == nil,
               "guessable ids and short deletion tokens are rejected")

        let recentCaptureIDs = (0..<14).map { _ in UUID() }

        let scratchpadViewSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/UI/Scratchpad/ScratchpadView.swift",
            encoding: .utf8)) ?? ""

        let scratchpadHitTargetContracts = [
            "Image(systemName: \"plus\")\n                    .font(.system(size: 12, weight: .semibold))\n                    .frame(width: 22, height: 22)\n                    .contentShape(Rectangle())",
            "Image(systemName: \"ellipsis\")\n                    .font(.system(size: 12, weight: .semibold))\n                    .frame(width: 22, height: 22)\n                    .contentShape(Rectangle())",
            ".fill(selected ? Color.accentColor.opacity(0.16) : Color.clear)\n                }\n                .contentShape(RoundedRectangle(cornerRadius: 6, style: .continuous))",
            "Image(systemName: service.isPinned ? \"pin.fill\" : \"pin\")\n                    .font(.system(size: 12, weight: .semibold))\n                    .frame(width: 22, height: 22)\n                    .contentShape(Rectangle())",
            "Image(systemName: \"xmark.circle.fill\")\n                    .font(.system(size: 14))\n                    .foregroundStyle(.secondary)\n                    .frame(width: 22, height: 22)\n                    .contentShape(Rectangle())",
        ]

        expect(scratchpadHitTargetContracts.allSatisfy { scratchpadViewSource.contains($0) },
               "the scratchpad tab bar and header controls keep their full padded hit targets")

        // An unpinned borderless Menu claims the free width of its row on
        // macOS 15 and starves whatever shares that row (issue #569), so the
        // rule is checked for every borderless menu in the app rather than for
        // the one this fix touches. Kill Process is the one
        // deliberate exception: its row controls take a shared minimum width
        // so the Kill button and the menu beside it line up down the list.
        let borderlessMenuException = "KillProcess/KillProcessView"

        var unpinnedBorderlessMenus: [String] = []

        let uiFiles = FileManager.default
            .enumerator(atPath: "Sources/Vorssaint/UI")?
            .compactMap { $0 as? String }
            .filter { $0.hasSuffix(".swift") && !$0.contains(" 2") } ?? []

        for file in uiFiles.sorted() {
            let path = "Sources/Vorssaint/UI/\(file)"
            guard !file.contains(borderlessMenuException),
                  let source = try? String(contentsOfFile: path, encoding: .utf8) else { continue }
            let lines = source.components(separatedBy: "\n")
            for (index, line) in lines.enumerated()
            where line.contains(".menuStyle(.borderlessButton)") {
                // Read to the end of the menu's own modifier chain: the next
                // line that is neither a modifier nor a comment belongs to
                // something else.
                var pinned = false
                var cursor = index + 1
                while cursor < lines.count {
                    let text = lines[cursor].trimmingCharacters(in: .whitespaces)
                    guard text.hasPrefix(".") || text.hasPrefix("//") else { break }
                    if text.hasPrefix(".fixedSize()") { pinned = true; break }
                    cursor += 1
                }
                if !pinned { unpinnedBorderlessMenus.append("\(file):\(index + 1)") }
            }
        }

        // The file count is part of the rule: an enumerator that finds nothing
        // would leave the list empty and pass while checking no menu at all.
        expect(!uiFiles.isEmpty && unpinnedBorderlessMenus.isEmpty,
               "every borderless menu keeps its own size, across \(uiFiles.count) "
               + "scanned files: \(unpinnedBorderlessMenus)")

        // `waitUntilAllOperationsAreFinished` has no deadline, and the window
        // walk that used it runs on the main thread while its operations run on
        // the shared dispatch pool. Once unrelated work had taken every worker
        // in that pool, not one operation started and the wait never returned,
        // taking the whole app with it (issue #971). The call is unusable here
        // for that reason, so the rule is the absence of it rather than the one
        // caller that was found holding it.
        var unboundedOperationWaits: [String] = []

        let appSources = FileManager.default
            .enumerator(atPath: "Sources/Vorssaint")?
            .compactMap { $0 as? String }
            .filter { $0.hasSuffix(".swift") && !$0.contains(" 2") } ?? []

        for file in appSources.sorted() {
            guard let source = try? String(contentsOfFile: "Sources/Vorssaint/\(file)",
                                           encoding: .utf8) else { continue }
            for (index, line) in source.components(separatedBy: "\n").enumerated()
            where line.contains("waitUntilAllOperationsAreFinished") {
                unboundedOperationWaits.append("\(file):\(index + 1)")
            }
        }

        expect(!appSources.isEmpty && unboundedOperationWaits.isEmpty,
               "no operation queue is waited on without a deadline: \(unboundedOperationWaits)")

        // Asking an application element for its role switches a Chromium app's
        // renderers into full accessibility mode for the rest of the process's
        // life (issue #953). It was fixed at the liveness probe, then found
        // again in the walk up an element's parents, where the chain above a
        // window is the application element — so the rule is the absence of
        // that read anywhere, rather than one grep per door somebody noticed.
        // This is a text scan, not dataflow: it knows an element is an
        // application element only when the same file names it in a `let x =
        // AXUIElementCreateApplication(...)`, and it reads the role attribute
        // and its element off one line. An application element handed to a
        // helper, stored in a property, or passed inline is still on review to
        // catch; both reads found so far were written the direct way.
        // Both scans below report real line numbers, so neither may filter its
        // array before enumerating: comments drop out in the predicate instead.
        func isCommentLine(_ line: String) -> Bool {
            line.trimmingCharacters(in: .whitespaces).hasPrefix("//")
        }

        var applicationRoleReads: [String] = []

        for file in appSources.sorted() {
            guard let source = try? String(contentsOfFile: "Sources/Vorssaint/\(file)",
                                           encoding: .utf8) else { continue }
            let lines = source.components(separatedBy: "\n")
            var applicationElements: Set<String> = []
            for line in lines where line.contains("AXUIElementCreateApplication(") {
                let assigned = (line.components(separatedBy: "=").first ?? "")
                    .trimmingCharacters(in: .whitespaces)
                    .components(separatedBy: " ")
                guard assigned.count == 2, assigned[0] == "let" || assigned[0] == "var" else { continue }
                applicationElements.insert(assigned[1])
            }
            for (index, line) in lines.enumerated()
            where line.contains("kAXRoleAttribute")
                && !isCommentLine(line)
                && applicationElements.contains(where: { line.contains("(\($0), ") }) {
                applicationRoleReads.append("\(file):\(index + 1)")
            }
        }

        expect(!appSources.isEmpty && applicationRoleReads.isEmpty,
               "no application element is ever asked for its role: \(applicationRoleReads)")

        // The scan above cannot see the other way in: a walk up kAXParent asks
        // `parent` for its role, and the application element is what sits above
        // the last window, so the element it reads is never named after one.
        // Two files carried the same walk, so the rule is that anywhere doing
        // it stops at the application element first, rather than a pin per copy.
        var unguardedParentWalks: [String] = []

        for file in appSources.sorted() {
            guard let source = try? String(contentsOfFile: "Sources/Vorssaint/\(file)",
                                           encoding: .utf8) else { continue }
            let lines = source.components(separatedBy: "\n")
            // Per occurrence and in order: a guard sitting anywhere in the file
            // would let a second walk go unguarded, and one written after the
            // read would let the read happen first, which is the whole failure.
            for (index, line) in lines.enumerated()
            where line.contains("role(of: parent)") && !isCommentLine(line) {
                // The window reads raw lines so the report above stays in real
                // line numbers; a commented-out guard must not count as one.
                let guarded = lines[max(0, index - 3)..<index]
                    .contains { $0.contains("isApplicationElement(parent)") && !isCommentLine($0) }
                if !guarded { unguardedParentWalks.append("\(file):\(index + 1)") }
            }
        }

        expect(!appSources.isEmpty && unguardedParentWalks.isEmpty,
               "a walk up the parent chain stops at the application element: \(unguardedParentWalks)")

        expect(ScratchpadRetention.sanitized("day") == .day
                && ScratchpadRetention.sanitized("week") == .week
                && ScratchpadRetention.sanitized("month") == .month
                && ScratchpadRetention.sanitized(nil) == .never
                && ScratchpadRetention.sanitized("yesterday") == .never,
               "scratchpad retention sanitizes to the allowed periods and falls back to never")

        expect(ScratchpadRetention.never.maxIdleInterval == nil
                && ScratchpadRetention.day.maxIdleInterval == 86_400
                && ScratchpadRetention.week.maxIdleInterval == 7 * 86_400
                && ScratchpadRetention.month.maxIdleInterval == 30 * 86_400,
               "scratchpad retention periods are a day, a week and thirty days")

        expect(ScratchpadSupport.dismissesOnOutsideClick(isPinned: false, exportModalActive: false)
                && !ScratchpadSupport.dismissesOnOutsideClick(isPinned: true, exportModalActive: false)
                && !ScratchpadSupport.dismissesOnOutsideClick(isPinned: false, exportModalActive: true),
               "the scratchpad pin and export dialog both block outside-click dismissal")

        let markdownPreview = ScratchpadSupport.markdownPreview(
            "# Heading\n\n**Bold** and *italic* with [link](https://example.com)\n\n- First\n- Second\n\n1. Third\n\n```\ncode\n```")

        expect(markdownPreview.map(\.kind) == [
                    .heading(1), .paragraph,
                    .unorderedListItem(depth: 1), .unorderedListItem(depth: 1),
                    .orderedListItem(ordinal: 1, depth: 1), .code
                ]
                && String(markdownPreview[0].text.characters) == "Heading"
                && String(markdownPreview[2].text.characters) == "First"
                && String(markdownPreview[5].text.characters) == "code"
                && markdownPreview[2].containerID == markdownPreview[3].containerID
                && markdownPreview[2].containerID != nil
                && markdownPreview[3].containerID != markdownPreview[4].containerID
                && markdownPreview[1].text.runs.contains {
                    $0.inlinePresentationIntent?.contains(.stronglyEmphasized) == true
                }
                && markdownPreview[1].text.runs.contains {
                    $0.inlinePresentationIntent?.contains(.emphasized) == true
                }
                && markdownPreview[1].text.runs.contains { $0.link != nil },
               "the scratchpad preview renders semantic blocks and inline formatting")

        expect(ScratchpadSupport.sanitizedBackgroundOpacity(0.7) == 0.7,
               "a scratchpad background opacity inside the range is kept")

        expect(ScratchpadSupport.sanitizedBackgroundOpacity(0)
                == ScratchpadSupport.backgroundOpacityRange.lowerBound
                && ScratchpadSupport.sanitizedBackgroundOpacity(-3)
                == ScratchpadSupport.backgroundOpacityRange.lowerBound,
               "the scratchpad background never goes below the familiar translucent style")

        expect(ScratchpadSupport.sanitizedBackgroundOpacity(4) == 1.0
                && ScratchpadSupport.sanitizedBackgroundOpacity(.nan) == 1.0
                && ScratchpadSupport.sanitizedBackgroundOpacity(.infinity) == 1.0,
               "a high or broken scratchpad opacity falls back to fully opaque")

        let scratchpadNow = Date(timeIntervalSince1970: 1_784_000_000)

        expect(!ScratchpadSupport.shouldClear(lastEdited: nil, now: scratchpadNow, retention: .day)
                && !ScratchpadSupport.shouldClear(lastEdited: scratchpadNow.addingTimeInterval(-90_000),
                                                  now: scratchpadNow, retention: .never)
                && !ScratchpadSupport.shouldClear(lastEdited: scratchpadNow.addingTimeInterval(-3_600),
                                                  now: scratchpadNow, retention: .day)
                && ScratchpadSupport.shouldClear(lastEdited: scratchpadNow.addingTimeInterval(-90_000),
                                                 now: scratchpadNow, retention: .day)
                && !ScratchpadSupport.shouldClear(lastEdited: scratchpadNow.addingTimeInterval(-90_000),
                                                  now: scratchpadNow, retention: .week)
                && ScratchpadSupport.shouldClear(lastEdited: scratchpadNow.addingTimeInterval(-8 * 86_400),
                                                 now: scratchpadNow, retention: .week)
                && !ScratchpadSupport.shouldClear(lastEdited: scratchpadNow.addingTimeInterval(60),
                                                  now: scratchpadNow, retention: .day),
               "the scratchpad only clears when a period is chosen and the last edit is older than it")

        let scratchpadExportName = ScratchpadSupport.exportFileName(title: "Scratchpad",
                                                                    date: scratchpadNow)

        expect(scratchpadExportName.hasPrefix("Scratchpad 20")
                && scratchpadExportName.hasSuffix(".txt")
                && scratchpadExportName.count == "Scratchpad ".count + 14,
               "scratchpad export file name is the title plus the local date")

        let firstPadID = UUID(uuidString: "00000000-0000-0000-0000-000000000001")!

        let secondPadID = UUID(uuidString: "00000000-0000-0000-0000-000000000002")!

        let thirdPadID = UUID(uuidString: "00000000-0000-0000-0000-000000000003")!

        let migratedScratchpad = ScratchpadDocument.initial(
            defaultName: "Scratchpad", id: firstPadID, text: "existing text",
            modifiedAt: scratchpadNow.addingTimeInterval(-120))

        let twoPads = migratedScratchpad.addingPad(defaultName: "Scratchpad", id: secondPadID)

        let threePads = twoPads?.addingPad(defaultName: "Scratchpad", id: thirdPadID)

        expect(threePads?.pads.map(\.name) == ["Scratchpad 1", "Scratchpad 2", "Scratchpad 3"]
                && threePads?.pads.map(\.id) == [firstPadID, secondPadID, thirdPadID]
                && threePads?.selectedID == thirdPadID,
               "new scratchpads append in order, receive clear names and become selected")

        expect(ScratchpadSupport.nextPadName(defaultName: "Scratchpad",
                                             existingNames: ["Scratchpad"]) == "Scratchpad 2",
               "an existing unnumbered scratchpad still occupies the first numbered slot")

        let renamedPad = threePads?.renaming(secondPadID, to: "  Work\nideas  ")

        expect(renamedPad?.pads[1].name == "Work ideas"
                && ScratchpadSupport.sanitizedPadName(String(repeating: "x", count: 50)).count
                    == ScratchpadDocument.maximumNameLength
                && threePads?.renaming(secondPadID, to: "   ") == nil,
               "scratchpad names stay single-line, bounded and never empty")

        let selectedFirst = renamedPad?.selecting(firstPadID)

        let removedFirst = selectedFirst?.removing(firstPadID)

        expect(removedFirst?.pads.map(\.id) == [secondPadID, thirdPadID]
                && removedFirst?.selectedID == secondPadID,
               "closing the selected scratchpad keeps order and selects its nearest neighbor")

        expect(migratedScratchpad.removing(firstPadID) == nil,
               "the last scratchpad cannot be closed")

        expect(ScratchpadSupport.requiresCloseConfirmation(migratedScratchpad.pads[0])
                && !ScratchpadSupport.requiresCloseConfirmation(
                    ScratchpadDocument.initial(defaultName: "Scratchpad").pads[0]),
               "only closing a scratchpad with content needs destructive confirmation")

        expect(ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "t",
                                                   commandOnly: true,
                                                   canCreatePad: true,
                                                   canClosePad: true) == .createPad,
               "Command-T creates a scratchpad tab while the pad is focused")

        expect(ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "t",
                                                   commandOnly: true,
                                                   canCreatePad: false,
                                                   canClosePad: true) == nil,
               "Command-T is idle at the scratchpad tab limit")

        expect(ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "w",
                                                   commandOnly: true,
                                                   canCreatePad: true,
                                                   canClosePad: true) == .closeSelectedPad,
               "Command-W closes the selected scratchpad tab when more than one remains")

        expect(ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "w",
                                                   commandOnly: true,
                                                   canCreatePad: true,
                                                   canClosePad: false) == .hidePad,
               "Command-W on the last scratchpad tab hides the pad")

        expect(ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "t",
                                                   commandOnly: false,
                                                   canCreatePad: true,
                                                   canClosePad: true) == nil
                && ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "w",
                                                       commandOnly: false,
                                                       canCreatePad: true,
                                                       canClosePad: true) == nil
                && ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "a",
                                                       commandOnly: true,
                                                       canCreatePad: true,
                                                       canClosePad: true) == nil,
               "scratchpad tab shortcuts need Command alone on T or W")

        expect(ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "W",
                                                   commandOnly: true,
                                                   canCreatePad: true,
                                                   canClosePad: true) == .closeSelectedPad,
               "Caps Lock preserves the scratchpad close shortcut")

        expect(ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: "z",
                                                   commandOnly: true,
                                                   canCreatePad: true,
                                                   canClosePad: true) == nil,
               "the AZERTY Z at the US W position must not close a scratchpad")

        expect(ScratchpadFocusedTabShortcut.action(charactersIgnoringModifiers: nil,
                                                   commandOnly: true,
                                                   canCreatePad: true,
                                                   canClosePad: true) == nil,
               "events without a character do not trigger scratchpad tab shortcuts")

        var limitedScratchpads = migratedScratchpad

        for _ in 2...ScratchpadDocument.maximumPadCount {
            limitedScratchpads = limitedScratchpads.addingPad(defaultName: "Scratchpad")!
        }

        expect(limitedScratchpads.pads.count == ScratchpadDocument.maximumPadCount
                && limitedScratchpads.addingPad(defaultName: "Scratchpad") == nil,
               "scratchpads keep a small fixed upper bound")

        var retainedScratchpads = ScratchpadDocument.initial(
            defaultName: "Scratchpad",
            id: firstPadID,
            text: "expired text",
            modifiedAt: scratchpadNow.addingTimeInterval(-90_000))

        retainedScratchpads = retainedScratchpads.addingPad(defaultName: "Scratchpad",
                                                             id: secondPadID)!

        retainedScratchpads.updateSelectedText("recent text",
                                               modifiedAt: scratchpadNow.addingTimeInterval(-300))

        retainedScratchpads.applyRetention(.day, now: scratchpadNow)

        expect(retainedScratchpads.pads[0].text.isEmpty
                && retainedScratchpads.pads[1].text == "recent text",
               "retention clears only scratchpads whose own text expired")

        let scratchpadDocumentData = renamedPad?.encoded()

        let decodedScratchpads = ScratchpadDocument.decoded(scratchpadDocumentData,
                                                            defaultName: "Scratchpad")

        expect(decodedScratchpads == renamedPad,
               "scratchpad text, names, order and selection round-trip together")

        let safeScratchpadExportName = ScratchpadSupport.exportFileName(
            title: "Work/Ideas: 1", date: scratchpadNow)

        expect(safeScratchpadExportName.hasPrefix("Work-Ideas- 1 ")
                && !safeScratchpadExportName.contains("/")
                && !safeScratchpadExportName.contains(":"),
               "scratchpad export names cannot turn tab names into path components")

        // Muting every microphone, not just the one the Mac is set to: an app
        // pointed at a device of its own has to go silent too.
        expect(MicMuteSupport.isOwnDevice(name: "Vorssaint Mixer")
                && !MicMuteSupport.isOwnDevice(name: "MacBook Air Microphone"),
               "the mute skips the app's own mixing device and no other")

        expect(!MicMuteSupport.shouldSaveVolume(nil)
                && !MicMuteSupport.shouldSaveVolume(0)
                && !MicMuteSupport.shouldSaveVolume(0.005)
                && MicMuteSupport.shouldSaveVolume(0.4),
               "a level worth restoring is remembered and a silent one never is")

        expect(MicMuteSupport.volumeToRestore(uid: "mic-a",
                                              saved: ["mic-a": 0.4, "mic-b": 0.9],
                                              legacy: 0.6) == 0.4
                && MicMuteSupport.volumeToRestore(uid: "mic-c",
                                                  saved: ["mic-a": 0.4],
                                                  legacy: 0.6) == 0.6
                && MicMuteSupport.volumeToRestore(uid: "mic-c", saved: [:], legacy: 0)
                    == MicMuteSupport.fallbackVolume
                && MicMuteSupport.volumeToRestore(uid: "mic-a",
                                                  saved: ["mic-a": 0],
                                                  legacy: 0) == MicMuteSupport.fallbackVolume,
               "each microphone gets its own level back, then the older single level, then a usable one")

        expect(MicMuteSupport.restoreTargets(recorded: ["mic-a", "gone"],
                                             present: ["mic-a", "mic-b"]) == ["mic-a"]
                && MicMuteSupport.restoreTargets(recorded: nil,
                                                 present: ["mic-a", "mic-b"]) == ["mic-a", "mic-b"]
                && MicMuteSupport.restoreTargets(recorded: [],
                                                 present: ["mic-a", "mic-b"]).isEmpty
                && MicMuteSupport.restoreTargets(recorded: ["mic-a"], present: []).isEmpty,
               "unmuting touches the microphones this app muted, every one with no record, and none when the record is empty")

        print("[generated-checks] RemappableScreenshotToolShortcuts \(checks)")
    }
}
