// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedDiskHelpersTests: XCTestCase {
    func testDiskHelpers() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        // Carried over: state an earlier section of MetricsTests.swift set and this one inherits.
        MetricFormat.locale = Locale(identifier: "en_US_POSIX")

        expect(DiskSupport.nvmeBytes(low: 2, high: nil) == 1_024_000,
               "NVMe data units convert to 512,000 byte units")

        expect(DiskSupport.nvmeBytes(low: 1, high: 1) == 2_199_023_256_064_000,
               "NVMe high data unit word is included")

        expectClose(DiskSupport.celsius(fromSMARTTemperature: 302) ?? -1, 28.85,
                    "SMART Kelvin temperature converts to Celsius")

        expectClose(DiskSupport.celsius(fromSMARTTemperature: 33) ?? -1, 33,
                    "SMART Celsius temperature is preserved")

        expect(DiskSupport.celsius(fromSMARTTemperature: 999) == nil,
               "SMART invalid temperature is ignored")

        expect(DiskSupport.healthPercent(fromPercentageUsed: 1) == 99,
               "SMART health subtracts percentage used")

        expect(DiskSupport.healthPercent(fromPercentageUsed: 150) == 0,
               "SMART health clamps exhausted drives")

        expect(DiskSupport.fileSystemLabel(type: "apfs") == "APFS",
               "file system label maps apfs")

        expect(DiskSupport.fileSystemLabel(type: " APFS \n") == "APFS",
               "file system label trims and ignores case")

        expect(DiskSupport.fileSystemLabel(type: "hfs", name: "Journaled HFS+") == "HFS+",
               "file system label maps journaled hfs")

        expect(DiskSupport.fileSystemLabel(type: "exfat") == "exFAT",
               "file system label keeps exFAT capitalization")

        expect(DiskSupport.fileSystemLabel(type: "ntfs") == "NTFS",
               "file system label maps ntfs")

        expect(DiskSupport.fileSystemLabel(type: "msdos", name: "Legacy FAT32") == "FAT32",
               "file system label reads FAT width from the name")

        expect(DiskSupport.fileSystemLabel(type: "msdos", name: "Legacy FAT16") == "FAT16",
               "file system label reads FAT16 from the name")

        expect(DiskSupport.fileSystemLabel(type: "msdos") == "FAT",
               "file system label falls back to plain FAT")

        expect(DiskSupport.fileSystemLabel(type: "cd9660") == "ISO 9660",
               "file system label maps optical media")

        expect(DiskSupport.fileSystemLabel(type: "udf") == "UDF",
               "file system label uppercases short unknown tokens")

        expect(DiskSupport.fileSystemLabel(type: "lifs") == "LIFS",
               "file system label keeps acronym-sized tokens")

        expect(DiskSupport.fileSystemLabel(type: "someverylongdriver") == nil,
               "file system label drops long driver tokens")

        expect(DiskSupport.fileSystemLabel(type: "a") == nil,
               "file system label drops single letters")

        expect(DiskSupport.fileSystemLabel(type: "123456") == nil,
               "file system label needs at least one letter")

        expect(DiskSupport.fileSystemLabel(type: "") == nil,
               "file system label ignores empty type")

        expect(DiskSupport.fileSystemLabel(type: nil) == nil,
               "file system label ignores missing type")

        let diskRate = MetricFormat.diskSpeed(
            previous: DiskIOCounters(read: 1_000, written: 500),
            current: DiskIOCounters(read: 3_048, written: 1_524),
            elapsed: 2
        )

        expectClose(diskRate.read, 1_024, "disk read speed uses elapsed time")

        expectClose(diskRate.write, 512, "disk write speed uses elapsed time")

        let resetDiskRate = MetricFormat.diskSpeed(
            previous: DiskIOCounters(read: 3_048, written: 1_524),
            current: DiskIOCounters(read: 2_000, written: 800),
            elapsed: 2
        )

        expectClose(resetDiskRate.read, 0, "disk read counter reset does not spike")

        expectClose(resetDiskRate.write, 0, "disk write counter reset does not spike")

        let smart = DiskSupport.smartReading(
            status: "Verified",
            vendorKeys: [
                "DATA_UNITS_READ_0": 2,
                "DATA_UNITS_WRITTEN_0": 4,
                "TEMPERATURE": 302,
                "PERCENTAGE_USED": 7,
                "POWER_CYCLES_0": 11,
                "POWER_ON_HOURS_0": 12,
                "UNSAFE_SHUTDOWNS_0": 13,
                "MEDIA_ERRORS_0": 14,
            ]
        )

        expect(smart?.status == "Verified", "SMART status is preserved")

        expect(smart?.totalReadBytes == 1_024_000, "SMART total read uses NVMe units")

        expect(smart?.totalWrittenBytes == 2_048_000, "SMART total written uses NVMe units")

        expectClose(smart?.temperatureCelsius ?? -1, 28.85, "SMART reading includes temperature")

        expect(smart?.healthPercent == 93, "SMART reading includes estimated health")

        expect(smart?.powerCycles == 11, "SMART reading includes power cycles")

        expect(smart?.powerOnHours == 12, "SMART reading includes power-on hours")

        expect(smart?.unsafeShutdowns == 13, "SMART reading includes unsafe shutdowns")

        expect(smart?.mediaErrors == 14, "SMART reading includes media errors")

        let diskDevice = DiskDeviceReading(
            id: "disk3s1",
            name: "Macintosh HD",
            mountPath: "/",
            bsdName: "disk3s1",
            wholeDisk: "disk3",
            ioCounterID: "disk3",
            fileSystem: "APFS",
            totalBytes: 245_000_000_000,
            freeBytes: 110_000_000_000,
            purgeableBytes: 28_000_000_000,
            usedBytes: 163_000_000_000,
            isInternal: true,
            isRemovable: false,
            isEjectable: false,
            smart: nil,
            readBytesPerSec: nil,
            writeBytesPerSec: nil,
            totalReadBytes: nil,
            totalWrittenBytes: nil
        )

        expect(diskDevice.purgeableBytes == 28_000_000_000, "disk reading preserves purgeable bytes")

        expectClose(diskDevice.usedFraction, 163.0 / 245.0, "disk used fraction reflects physical used bytes")

        print("[generated-checks] DiskHelpers \(checks)")
    }
}
