// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedFanControlSafetyPolicyTests: XCTestCase {
    func testFanControlSafetyPolicy() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let watchdogEnd = Date(timeIntervalSince1970: 2_000)

        for language in AppLanguage.allCases {
            let strings = FeatureStrings.fanControl(language)
            let values = Mirror(reflecting: strings).children.compactMap { $0.value as? String }
            expect(values.count == 42 && values.allSatisfy { !$0.isEmpty },
                   "fan control has every localized field for \(language.rawValue)")
            expect(values.allSatisfy { !$0.contains("—") },
                   "fan control text uses human punctuation for \(language.rawValue)")
            expectFormat(strings.fanNameFormat, ["d"],
                         "fan name format stays valid for \(language.rawValue)")
            expectFormat(strings.rpmFormat, ["d"],
                         "fan speed format stays valid for \(language.rawValue)")
            expectFormat(strings.currentRPMFormat, ["d"],
                         "current fan speed format stays valid for \(language.rawValue)")
            expectFormat(strings.targetRPMFormat, ["d"],
                         "target fan speed format stays valid for \(language.rawValue)")
        }

        expect(FanControlFeatureStrings.ru.rpmFormat == "%d об/мин"
                && FanControlFeatureStrings.de.rpmFormat == "%d U/min"
                && FanControlFeatureStrings.fr.rpmFormat == "%d tr/min",
               "existing localized RPM units stay intact")

        let legacyFanSnapshot = Data(#"{"fans":[],"isCooling":false}"#.utf8)

        let fanMigrationSuite = "com.vorssaint.tests.fan-migration.\(UUID().uuidString)"

        let windowLayoutPollingKeys = [
            DefaultsKey.windowLayoutShortcutsEnabled,
            DefaultsKey.windowGestureEnabled,
            DefaultsKey.windowEdgeSnapEnabled,
        ]

        expect(BrightnessSupport.shortcutDisplay(followsPointer: true, pointerDisplay: 2,
                   primaryDisplay: 1, eligible: [1, 2]) == 2,
               "display shortcuts follow the pointer onto an external monitor")

        expect(BrightnessSupport.shortcutDisplay(followsPointer: false, pointerDisplay: 2,
                   primaryDisplay: 1, eligible: [1, 2]) == 1,
               "display shortcuts use the primary display when pointer routing is off")

        expect(BrightnessSupport.shortcutDisplay(followsPointer: true, pointerDisplay: 2,
                   primaryDisplay: 1, eligible: [1]) == nil,
               "an unavailable pointer target never changes a different display")

        expect(BrightnessSupport.shortcutDisplay(followsPointer: true, pointerDisplay: nil,
                   primaryDisplay: 1, eligible: [1]) == nil,
               "a missing pointer target does not dim the primary display")

        expect(BrightnessSupport.shortcutDisplay(followsPointer: false, pointerDisplay: 2,
                   primaryDisplay: 1, eligible: [2]) == nil,
               "an unavailable primary display never redirects the shortcut")

        print("[generated-checks] FanControlSafetyPolicy \(checks)")
    }
}
