// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedSnippetLibraryIssue340Tests: XCTestCase {
    func testSnippetLibraryIssue340() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let workMail = TextSnippet(name: "Work mail", trigger: ";wmail", replacement: "work@x.com",
                                   expansion: .afterDelimiter, enabled: true, folder: "Work")

        let workSig = TextSnippet(name: "Signature", trigger: ";sig", replacement: "Best, V",
                                  expansion: .afterDelimiter, enabled: true, folder: "Work")

        let homeNote = TextSnippet(name: "Address", trigger: ";addr", replacement: "Elm St 1",
                                   expansion: .afterDelimiter, enabled: true, folder: "Home")

        let loose = TextSnippet(name: "Loose", trigger: ";loose", replacement: "loose text",
                                expansion: .afterDelimiter, enabled: true)

        let hidden = TextSnippet(name: "Hidden", trigger: ";hide", replacement: "hidden",
                                 expansion: .afterDelimiter, enabled: true, showsInLibrary: false)

        let disabled = TextSnippet(name: "Off", trigger: ";off", replacement: "off",
                                   expansion: .afterDelimiter, enabled: false)

        let libraryPool = [loose, workMail, hidden, homeNote, disabled, workSig]

        let allSections = TextSnippetSupport.librarySections(libraryPool, query: "")

        expect(allSections.map(\.folder) == ["Home", "Work", ""],
               "library folders come alphabetically with loose snippets closing the list")

        expect(allSections.last?.snippets == [loose],
               "disabled and hidden snippets never reach the library")

        expect(allSections[1].snippets == [workMail, workSig],
               "snippets keep their stored order inside a folder")

        expect(TextSnippetSupport.libraryRows(allSections).map(\.name)
                == ["Address", "Work mail", "Signature", "Loose"],
               "the flat row list walks the sections in reading order")

        expect(TextSnippetSupport.librarySections(libraryPool, query: "WORK").flatMap(\.snippets).count == 2,
               "searching matches the folder name regardless of casing")

        expect(TextSnippetSupport.librarySections(libraryPool, query: ";addr").flatMap(\.snippets) == [homeNote],
               "searching matches the trigger")

        expect(TextSnippetSupport.librarySections(libraryPool, query: "loose text").flatMap(\.snippets) == [loose],
               "searching matches the snippet text")

        expect(TextSnippetSupport.librarySections(libraryPool, query: "signat").flatMap(\.snippets) == [workSig],
               "searching matches the name")

        expect(TextSnippetSupport.librarySections(libraryPool, query: "zzz").isEmpty,
               "a search with no matches yields no sections")

        expect(TextSnippetSupport.librarySections(libraryPool, query: "  ").map(\.folder) == ["Home", "Work", ""],
               "a whitespace-only search counts as empty")

        expect(TextSnippetSupport.folderSuggestions(libraryPool) == ["Home", "Work"],
               "folder suggestions are distinct and alphabetical")

        expect(TextSnippetSupport.sanitizedFolder("  Work \n") == "Work",
               "folder names lose surrounding whitespace")

        expect(TextSnippetSupport.sanitizedFolder("   ") == "",
               "a whitespace-only folder means no folder")

        print("[generated-checks] SnippetLibraryIssue340 \(checks)")
    }
}
