// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedMediaSizeTargetsTests: XCTestCase {
    func testMediaSizeTargets() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let sizeTargetStrings: [(String, Strings)] = [
            ("en-US", .enUS), ("pt-BR", .ptBR), ("tr", .tr), ("ru", .ru), ("es", .es),
            ("de", .de), ("fr", .fr), ("it", .it), ("ja", .ja), ("ko", .ko),
            ("zh-Hans", .zhHans), ("zh-HK", .zhHK), ("zh-TW", .zhTW),
        ]

        for (name, strings) in sizeTargetStrings {
            expect(!strings.mediaSizingResolution.isEmpty
                    && !strings.mediaSizingFileSize.isEmpty
                    && !strings.mediaTargetSize.isEmpty
                    && !strings.mediaTargetSizeHint.isEmpty
                    && !strings.mediaErrorTargetTooSmall.isEmpty
                    && !strings.mediaMegabytesSuffix.isEmpty,
                   "\(name) names the size target controls")
        }

        // This run ends in exit(), which skips every defer, so scratch built
        // in the temp area is listed here and handed back before it reports.
        // The three defers that used to do it never ran once: a directory per
        // run had been piling up in the system's temp area for as long as the
        // suite has existed.
        var scratchPaths: [URL] = []

        let uniqueDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("vorssaint-media-unique-\(UUID().uuidString)", isDirectory: true)

        try? FileManager.default.createDirectory(at: uniqueDir, withIntermediateDirectories: true)

        scratchPaths.append(uniqueDir)

        let longBaseName = String(repeating: "😀", count: 100)

        for language in AppLanguage.allCases {
            let strings = MediaImageConverterStrings.localized(language)
            let values = Mirror(reflecting: strings).children.compactMap { $0.value as? String }
            expect(values.count == 56 && values.allSatisfy { !$0.isEmpty },
                   "every image converter string is set for \(language.rawValue)")
            expect(values.allSatisfy { !$0.contains("—") },
                   "no em-dash in visible image converter strings (\(language.rawValue))")
            expect(strings.filesSelectedFormat.contains("%d")
                   && strings.profileDefaultNameFormat.contains("%d")
                   && strings.savedBytesFormat.contains("%@")
                   && strings.grewBytesFormat.contains("%@")
                   && strings.batchSavedFormat.contains("%d")
                   && strings.batchPartialFormat.filter { $0 == "%" }.count == 2
                   && strings.batchSummaryHeaderFormat.filter { $0 == "%" }.count == 2
                   && strings.batchSummaryItemFormat.filter { $0 == "%" }.count == 2,
                   "image converter formats keep their arguments in \(language.rawValue)")
        }

        let mediaInput = URL(fileURLWithPath: "/tmp/Clip.mov")

        let hiddenMediaInput = URL(fileURLWithPath: "/tmp/.Clip.mov")

        let extensionOnlyMediaInput = URL(fileURLWithPath: "/tmp/.mov")

        let emptyBaseMediaInput = URL(fileURLWithPath: "/tmp/...")

        let mediaVisibilityDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("vorssaint-media-visibility-\(UUID().uuidString)", isDirectory: true)

        try? FileManager.default.createDirectory(at: mediaVisibilityDir,
                                                 withIntermediateDirectories: true)

        scratchPaths.append(mediaVisibilityDir)

        let visibleMediaOutput = mediaVisibilityDir.appendingPathComponent("Visible.gif")

        FileManager.default.createFile(atPath: visibleMediaOutput.path,
                                       contents: Data([0x47, 0x49, 0x46, 0x38]),
                                       attributes: nil)

        var percentFieldAttached = false

        let savedMixerVolumes = ["com.apple.Safari": 0.35, "com.apple.Music": 1.4]

        print("[generated-checks] MediaSizeTargets \(checks)")
    }
}
