// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedASleepingClockTests: XCTestCase {
    func testASleepingClock() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        for shareService in ["Sources/Vorssaint/Services/QuickTools/ScreenshotShareService.swift",
                             "Sources/Vorssaint/Services/Recorder/RecordingShareService.swift"] {
            let shareCode = ((try? String(contentsOfFile: shareService, encoding: .utf8)) ?? "")
                .components(separatedBy: "\n")
                .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
                .joined(separator: "\n")
            expect(shareCode.contains("NSWorkspace.didWakeNotification"),
                   "\(shareService) recomputes share link expiry on wake, which its sleeping clock missed")
        }

        // The confirmation HUD is a hand-laid AppKit panel, so its width is
        // pinned as source shape. It used to be a fixed 300pt, which clipped
        // the longer translations. Sizing it from a separate
        // NSString measurement of the same text would leave whatever inset
        // the label's cell adds unaccounted for -- the labels have to be the
        // ones asked.
        let quitHUDSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/UI/QuitProtection/QuitProtectionHUD.swift",
            encoding: .utf8)) ?? ""

        expect(quitHUDSource.count > 1_000,
               "the quit protection HUD source is readable (\(quitHUDSource.count) bytes)")

        let quitHUDCode = quitHUDSource
            .split(separator: "\n", omittingEmptySubsequences: false)
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .joined(separator: "\n")

        expect(quitHUDCode.contains("title.fittingSize.width")
                && quitHUDCode.contains("detail.fittingSize.width"),
               "the confirmation HUD takes its width from the labels that draw the text")

        expect(!quitHUDCode.contains("size(withAttributes:"),
               "the confirmation HUD does not size itself from a separate text measurement")

        let quitHUDShow = quitHUDCode
            .components(separatedBy: "func show(title: String, detail: String").last ?? ""

        let quitHUDShowBody = quitHUDShow.components(separatedBy: "\n    func ").first ?? ""

        if let filled = quitHUDShowBody.range(of: "content.update("),
           let sized = quitHUDShowBody.range(of: "fittingSize(content)"),
           let applied = quitHUDShowBody.range(of: "setContentSize(size)") {
            expect(filled.lowerBound < sized.lowerBound && sized.lowerBound < applied.lowerBound,
                   "the confirmation HUD fills its labels, then measures them, then resizes")
        } else {
            expect(false,
                   "the confirmation HUD's show() fills the labels, measures them and resizes")
        }

        print("[generated-checks] ASleepingClock \(checks)")
    }
}
