// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedTheMacSOwnSettingsPanesTests: XCTestCase {
    func testTheMacSOwnSettingsPanes() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let openablePane: [String: Any] = [
            "EXAppExtensionAttributes": [
                "SettingsExtensionAttributes": [
                    "allowsXAppleSystemPreferencesURLScheme": true,
                    "legacyPrefPaneBundleName": "Legacy.prefPane",
                ],
            ],
        ]

        expect(CommandBarSystemSettingsSupport.isOpenablePane(info: openablePane),
               "a pane that answers to the system settings address is one the bar can open")

        expect(!CommandBarSystemSettingsSupport.isOpenablePane(info: [
            "EXAppExtensionAttributes": [
                "SettingsExtensionAttributes": ["allowsXAppleSystemPreferencesURLScheme": false],
            ],
        ]) && !CommandBarSystemSettingsSupport.isOpenablePane(info: ["CFBundleName": "Thumbnails"]),
               "a thumbnailer, and a pane with no address, are not rows")

        expect(CommandBarSystemSettingsSupport.legacyPaneName(info: openablePane)
                == "Legacy.prefPane"
                && CommandBarSystemSettingsSupport.legacyPaneName(info: ["a": 1]) == nil,
               "the older pane is followed only where the newer one names it")

        expect(CommandBarSystemSettingsSupport.paneName(localizedDisplayName: "Coverage & Support",
                                                        displayName: "CoveragePane_Internal",
                                                        bundleName: "Coverage",
                                                        fileName: "CoverageSettings.appex")
                == "Coverage & Support",
               "a pane is called what System Settings calls it")

        expect(CommandBarSystemSettingsSupport.paneName(localizedDisplayName: nil,
                                                        displayName: "  ",
                                                        bundleName: nil,
                                                        fileName: "VPN.appex") == "VPN",
               "a pane that declares no name at all still gets one")

        // Every pane names its own groups, so all of them are read, in a fixed
        // order: one Mac and the next must produce the same words.
        expect(CommandBarSystemSettingsSupport.keywords(fromSearchTerms: [
            "bSection": ["localizableStrings": [["title": "Brillo", "index": "aclarar, atenuar"]]],
            "aSection": ["localizableStrings": [["title": "Alinear", "index": "espejo,  , Alinear"]]],
        ]) == "Alinear espejo Brillo aclarar atenuar",
               "the words a pane answers to are read from every group and never repeat")

        expect(CommandBarSystemSettingsSupport.keywords(fromSearchTerms: ["Main": "not a group"])
                .isEmpty,
               "a search index in a shape nobody recognizes is no words, not a crash")

        expect(CommandBarSystemSettingsSupport.keywords(fromSearchTerms: [
            "a": ["localizableStrings": [["title": "one", "index": "two, three"]]],
        ], limit: 2) == "one two",
               "one pane never contributes more words than the ranking can use")

        let longPaneTerms = (1...45).map { ["title": "term\($0)", "index": ""] }

        expect(CommandBarSystemSettingsSupport.keywords(fromSearchTerms: [
            "Main": ["localizableStrings": longPaneTerms],
        ]).contains("term45"),
               "important terms beyond the old forty-word cutoff remain searchable")

        expect(Set(AppLanguage.allCases.map(CommandBarSystemSettingsSupport.resourceFolder)).count
                == AppLanguage.allCases.count,
               "each language reads its own words, so no two share a folder")

        print("[generated-checks] TheMacSOwnSettingsPanes \(checks)")
    }
}
