// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedRegisteredDefaultsTests: XCTestCase {
    func testRegisteredDefaults() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        expect(AppAppearance.sanitized(nil) == .system
                && AppAppearance.sanitized("nonsense") == .system,
               "an unknown stored appearance falls back to the system one")

        expect(AppAppearance.sanitized("dark") == .dark && AppAppearance.sanitized("light") == .light,
               "stored appearance values survive a relaunch")

        expect(AppAppearance.allCases.map(\.rawValue) == ["system", "light", "dark"],
               "appearance raw values are persisted keys and their order is the picker order")

        expect(!KeepAwakeAutomationSupport.hasExternalDisplay(builtInFlags: []),
               "no online display does not count as an external display")

        expect(!KeepAwakeAutomationSupport.hasExternalDisplay(builtInFlags: [true]),
               "the built-in screen does not count as an external display")

        expect(KeepAwakeAutomationSupport.hasExternalDisplay(builtInFlags: [true, false]),
               "an online non-built-in screen counts as an external display")

        expect(!KeepAwakeAutomationSupport.selectedAppsAreRunning(
            selectedBundleIDs: [],
            runningBundleIDs: ["com.example.app"]
        ), "an empty selected-app list never matches a running app")

        expect(!KeepAwakeAutomationSupport.selectedAppsAreRunning(
            selectedBundleIDs: ["com.example.app"],
            runningBundleIDs: ["com.other.app"]
        ), "a selected app that is not running does not match")

        expect(KeepAwakeAutomationSupport.selectedAppsAreRunning(
            selectedBundleIDs: ["com.example.app", "com.other.app"],
            runningBundleIDs: ["com.helper", "com.example.app"]
        ), "any selected app that is running matches, focused or not")

        let combinedKeepAwakeConditions = KeepAwakeAutomationSupport.matchingConditions(
            externalDisplayEnabled: true,
            externalDisplayConnected: true,
            powerEnabled: true,
            connectedToPower: true,
            runningAppsEnabled: true,
            selectedAppsRunning: true
        )

        expect(combinedKeepAwakeConditions == [.externalDisplay, .power, .runningApps],
               "enabled Keep Awake conditions combine with OR behavior")

        expect(KeepAwakeAutomationSupport.matchingConditions(
            externalDisplayEnabled: false,
            externalDisplayConnected: false,
            powerEnabled: false,
            connectedToPower: false,
            runningAppsEnabled: true,
            selectedAppsRunning: true
        ) == [.runningApps], "a running selected app matches the running-apps condition")

        expect(KeepAwakeAutomationSupport.matchingConditions(
            externalDisplayEnabled: false,
            externalDisplayConnected: false,
            powerEnabled: false,
            connectedToPower: false,
            runningAppsEnabled: true,
            selectedAppsRunning: false
        ).isEmpty, "running-apps stays off when none of the selected apps are open")

        expect(KeepAwakeAutomationSupport.action(
            featureAvailable: true,
            matchingConditions: [.externalDisplay],
            sessionActive: false,
            automaticSessionActive: false
        ) == .activate, "an external display starts the automatic session")

        expect(KeepAwakeAutomationSupport.action(
            featureAvailable: true,
            matchingConditions: [],
            sessionActive: true,
            automaticSessionActive: true
        ) == .deactivate, "clearing every matching condition ends the automatic session")

        expect(KeepAwakeAutomationSupport.action(
            featureAvailable: true,
            matchingConditions: [],
            sessionActive: true,
            automaticSessionActive: false
        ) == .none, "clearing automatic conditions does not end a manual session")

        expect(KeepAwakeAutomationSupport.isScreenLocked(
            sessionDictionary: ["CGSSessionScreenIsLocked": true]
        ), "the Keep Awake lock guard reads a locked session")

        expect(!KeepAwakeAutomationSupport.isScreenLocked(
            sessionDictionary: ["CGSSessionScreenIsLocked": false]
        ), "the Keep Awake lock guard reads an unlocked session")

        expect(!KeepAwakeAutomationSupport.isScreenLocked(sessionDictionary: nil),
               "an unreadable lock state does not strand Keep Awake in a pause")

        let sleepDisabledReport = """
        System-wide power settings:
         SleepDisabled\t\t1
        Currently in use:
         standby              1
        """

        let sleepEnabledReport = """
        System-wide power settings:
         SleepDisabled\t\t0
        Currently in use:
         standby              1
        """

        expect(SudoersSupport.sleepDisabled(inPmsetOutput: sleepDisabledReport),
               "a pmset report with SleepDisabled 1 reads as lid sleep disabled")

        expect(!SudoersSupport.sleepDisabled(inPmsetOutput: sleepEnabledReport),
               "a pmset report with SleepDisabled 0 reads as lid sleep enabled")

        expect(!SudoersSupport.sleepDisabled(inPmsetOutput: ""),
               "an empty pmset report reads as lid sleep enabled")

        // The rule is granted by uid so every short name works, including the
        // email-style ones SSO enrollment produces (#915). The uid renders as
        // bare digits and the rest is a fixed literal, so the whole line must
        // stay inside a character set that neither sudoers nor a single-quoted
        // shell string can read as anything but itself.
        expect(SudoersSupport.clamshellRule(uid: 501)
               == "#501 ALL=(root) NOPASSWD: /usr/bin/pmset disablesleep 1, /usr/bin/pmset disablesleep 0",
               "the closed-lid sudoers rule grants pmset disablesleep to the uid")

        let shortcutSuite = "vorss.tests.switcher.shortcut"

        // The session-start layout pass reads usesWindowRow, which now depends
        // on the session scope; teardown resets the scope to .allApps, so the
        // scope must be assigned before the layout pass or a window-scoped
        // panel is sized for the grouped layout on its first frame.
        let switcherSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/Switcher/AppSwitcher.swift",
            encoding: .utf8)) ?? ""

        // Ends on whatever declaration comes next rather than naming the
        // neighbour: a rename would find no separator, leave the slice running
        // to end of file, and quietly restore the whole-file search this
        // replaced — a failure that makes the slice bigger, so an empty check
        // cannot see it. Hence the count assertion below.
        let finishSessionParts = (switcherSource.components(separatedBy: "private func finishPendingSession")
            .last ?? "").components(separatedBy: "\n    private func ")

        let finishSessionBody = finishSessionParts.first ?? ""

        expect(finishSessionParts.count > 1,
               "the App Switcher ordering guard finds the end of finishPendingSession")

        let switcherCode = finishSessionBody
            .split(separator: "\n", omittingEmptySubsequences: false)
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .joined(separator: "\n")

        let scopeAssign = switcherCode.range(of: "sessionScope = pending.scope")

        let startLayout = switcherCode.range(of: "recomputeLayouts(for: list)")

        expect(!finishSessionBody.isEmpty,
               "the App Switcher session-start ordering guard finds finishPendingSession")

        expect(scopeAssign != nil && startLayout != nil
               && scopeAssign!.lowerBound < startLayout!.lowerBound,
               "the App Switcher session scope is assigned before the session-start layout pass")

        // Trimming the list to one display (issue #1391) can drop the window
        // that was in front, and then index 0 is no longer where the session
        // started. The initial selection has to follow what the list holds.
        expect(!switcherCode.contains("hasForegroundItem: source != nil")
               && switcherCode.contains("hasForegroundItem: listedSource != nil"),
               "the App Switcher initial selection follows the window the trimmed list still holds")

        let regularBundlePaths: [pid_t: String] = [101: "/Applications/Primary.app"]

        let dockIconBundle = FileManager.default.temporaryDirectory
            .appendingPathComponent("vorssaint-dock-icon-\(UUID().uuidString).app")

        let dockIconResources = dockIconBundle.appendingPathComponent("Contents/Resources")

        try? FileManager.default.createDirectory(at: dockIconResources,
                                                 withIntermediateDirectories: true)

        let lightDockIcon = dockIconResources.appendingPathComponent("chosen-light.png")

        let darkDockIcon = dockIconResources.appendingPathComponent("chosen-dark-color.png")

        FileManager.default.createFile(atPath: lightDockIcon.path, contents: Data([0]))

        FileManager.default.createFile(atPath: darkDockIcon.path, contents: Data([1]))

        print("[generated-checks] RegisteredDefaults \(checks)")
    }
}
