// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedBrightnessKeyBaseIssue370Tests: XCTestCase {
    func testBrightnessKeyBaseIssue370() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let pressed = Date(timeIntervalSince1970: 1_800_000_000)

        expect(BrightnessSupport.trustsRememberedLevel(lastKnownAt: pressed,
                                                       now: pressed.addingTimeInterval(1),
                                                       window: 3),
               "a level written a moment ago is still the running value")

        expect(!BrightnessSupport.trustsRememberedLevel(lastKnownAt: pressed,
                                                        now: pressed.addingTimeInterval(3),
                                                        window: 3),
               "a level older than the window is asked about again")

        expect(!BrightnessSupport.trustsRememberedLevel(lastKnownAt: nil,
                                                        now: pressed, window: 3),
               "a display never written to is asked about")

        expect(!BrightnessSupport.trustsRememberedLevel(lastKnownAt: pressed.addingTimeInterval(60),
                                                        now: pressed, window: 3),
               "a clock that jumped backwards never makes a stale level look fresh")

        // The step itself is unchanged; what changed is the value it starts
        // from, so the arithmetic stays pinned.
        expect(BrightnessSupport.steppedBrightness(0.8, delta: 1 / 16.0) > 0.8
                && BrightnessSupport.steppedBrightness(0.0, delta: 1 / 16.0) > 0,
               "a step still moves in the direction asked for")

        print("[generated-checks] BrightnessKeyBaseIssue370 \(checks)")
    }
}
