// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedPreciseVolumeRollerTests: XCTestCase {
    func testPreciseVolumeRoller() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        var volumeGate = PreciseVolumeRollerGate()

        expect(volumeGate.accepts(.up, at: 100.00),
               "precise volume accepts the first wheel step")

        expect(!volumeGate.accepts(.up, at: 100.01),
               "precise volume drops repeats that arrive inside the spacing window")

        expect(volumeGate.accepts(.up, at: 100.05),
               "precise volume accepts a later step in the same direction")

        var reversalGate = PreciseVolumeRollerGate()

        expect(reversalGate.accepts(.up, at: 200.00),
               "precise volume reversal setup accepts the initial direction")

        expect(!reversalGate.accepts(.down, at: 200.08),
               "precise volume ignores the first opposite pulse inside the reversal window")

        expect(!reversalGate.accepts(.down, at: 200.16),
               "precise volume waits for a stable opposite direction")

        expect(reversalGate.accepts(.down, at: 200.24),
               "precise volume accepts the confirmed opposite direction")

        var oldDirectionGate = PreciseVolumeRollerGate()

        expect(oldDirectionGate.accepts(.up, at: 300.00),
               "precise volume accepts first old-direction step")

        expect(oldDirectionGate.accepts(.down, at: 300.40),
               "precise volume accepts an opposite step after the reversal window")

        var fastStreamGate = PreciseVolumeRollerGate()

        let fastAccepted = stride(from: 400.00, through: 400.10, by: 0.02)
            .filter { fastStreamGate.accepts(.up, at: $0) }

        expect(fastAccepted.count == 3,
               "precise volume rate-limits sustained fast input instead of starving it")

        expect(PreciseVolumeMediaKey.volumeUp.rollerDirection == .up
                && PreciseVolumeMediaKey.volumeDown.rollerDirection == .down
                && PreciseVolumeMediaKey.mute.rollerDirection == nil,
               "precise volume only remaps volume up and down media keys")

        print("[generated-checks] PreciseVolumeRoller \(checks)")
    }
}
