// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedModifyingMouseTapsAreHandedBackAcrossASessionSwitchTests: XCTestCase {
    func testModifyingMouseTapsAreHandedBackAcrossASessionSwitch() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        // The tap owners cannot be reached from this list (they need the event
        // chain), so the wiring is pinned as text: each service follows the
        // session and asks before re-arming a tap the window server disabled.
        // Comments are stripped so prose naming the API cannot answer for it.
        let sessionActivitySource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/SessionActivity.swift",
            encoding: .utf8)) ?? ""

        expect(sessionActivitySource.contains("sessionDidResignActiveNotification")
                && sessionActivitySource.contains("sessionDidBecomeActiveNotification"),
               "the session watcher follows both halves of a fast user switch")

        let mouseAccelerationSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/MouseAcceleration/MouseAccelerationService.swift",
            encoding: .utf8)) ?? ""

        expect(mouseAccelerationSource.contains("SessionActivitySupport.isOnConsole("),
               "mouse acceleration shares the safe initial session-state fallback")

        for tapOwner in ["Sources/Vorssaint/Services/ScrollInverter.swift",
                         "Sources/Vorssaint/Services/SmoothScrollService.swift",
                         "Sources/Vorssaint/Services/MouseNavigation/MouseNavigationService.swift",
                         "Sources/Vorssaint/Services/MouseButtons/MouseButtonShortcutService.swift",
                         "Sources/Vorssaint/Services/MiddleClick/MiddleClickService.swift",
                         "Sources/Vorssaint/Services/QuitProtection/QuitProtectionService.swift",
                         "Sources/Vorssaint/Services/RadialMenu/RadialMenuService.swift",
                         "Sources/Vorssaint/Services/WindowLayout/WindowLayoutService.swift",
                         "Sources/Vorssaint/Services/WindowMaximizer.swift",
                         "Sources/Vorssaint/Services/Finder/FinderCutPaste.swift",
                         "Sources/Vorssaint/Services/Finder/FinderRenameService.swift",
                         "Sources/Vorssaint/Services/KeyboardDebounce/KeyboardDebounceService.swift",
                         "Sources/Vorssaint/Services/SuperKey/SuperKeyService.swift",
                         "Sources/Vorssaint/Services/ShortcutRecordingTap.swift",
                         "Sources/Vorssaint/Services/Switcher/AppSwitcher.swift",
                         "Sources/Vorssaint/Services/Snippets/TextSnippetService.swift",
                         "Sources/Vorssaint/Services/Audio/PreciseVolumeRollerService.swift",
                         "Sources/Vorssaint/Services/DockClick/DockClickService.swift",
                         "Sources/Vorssaint/Services/Display/BrightnessService.swift"] {
            let source = (try? String(contentsOfFile: tapOwner, encoding: .utf8)) ?? ""
            expect(!source.isEmpty, "\(tapOwner) reads back for its session-switch check")
            let code = source.components(separatedBy: "\n")
                .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
                .joined(separator: "\n")
            expect(code.contains("SessionActivity.shared.onChange"),
                   "\(tapOwner) rebuilds its tap when the session comes back")
            let rearm = code.components(separatedBy: "tapDisabledByTimeout")
                .dropFirst().first?.components(separatedBy: "return").first ?? ""
            expect(rearm.contains("SessionActivity.shared.isActive"),
                   "\(tapOwner) does not re-arm a disabled tap into a switched-away session")
            if tapOwner.contains("MouseNavigation")
                || tapOwner.contains("MouseButtonShortcut")
                || tapOwner.contains("MiddleClick")
                || tapOwner.contains("QuitProtection")
                || tapOwner.contains("RadialMenu")
                || tapOwner.contains("ShortcutRecordingTap") {
                expect(rearm.contains("AXIsProcessTrusted()"),
                       "\(tapOwner) does not keep a modifying tap alive after Accessibility is lost")
            }
            // Switching a tap off leaves the process owning it, which is what
            // the window server waits on; teardown must invalidate the port,
            // either here or through the pointer thread that owns the source.
            expect(code.contains("CFMachPortInvalidate")
                    || code.contains("PointerTapRunLoop.remove("),
                   "\(tapOwner) hands its tap back rather than only disabling it")
        }

        // The taps that filter ordinary clicks and wheel events are served by
        // a thread of their own. On the main run loop each of those events
        // waits for whatever this app is drawing or asking Accessibility,
        // which is felt as click lag in whatever app is in front.
        let pointerTapSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/PointerTapRunLoop.swift",
            encoding: .utf8)) ?? ""

        expect(pointerTapSource.contains("CFMachPortInvalidate"),
               "the pointer thread hands back the port of every tap it gives up")

        expect(pointerTapSource.contains("qualityOfService = .userInteractive"),
               "the pointer thread is scheduled as input work")

        for pointerTapOwner in ["Sources/Vorssaint/Services/ScrollInverter.swift",
                                "Sources/Vorssaint/Services/MiddleClick/MiddleClickService.swift"] {
            let source = (try? String(contentsOfFile: pointerTapOwner, encoding: .utf8)) ?? ""
            let code = source.components(separatedBy: "\n")
                .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
                .joined(separator: "\n")
            expect(code.contains("PointerTapRunLoop.add("),
                   "\(pointerTapOwner) serves its tap on the pointer thread")
            expect(!code.contains("CFRunLoopGetMain()"),
                   "\(pointerTapOwner) keeps its tap off the main run loop")
        }

        // Disabling a tap and dropping the last Swift reference does not hand
        // the port back: CGGetEventTapList still reports the tap against this
        // process, one more per start/stop cycle, for the life of the process.
        // Only CFMachPortInvalidate deregisters it. Counted per tap rather than
        // per file, because BrightnessService and SuperKeyService own two taps
        // each and WindowLayoutService three, and on comment-stripped source,
        // as in the per-service check above, so prose naming the API cannot
        // answer for a missing call. A margin does not cover a tap added later:
        // MouseClickDebounceService's two invalidations are both on its one
        // tap. The owners reached are counted too, because a file with no
        // literal CGEvent.tapCreate is skipped, so moving the call behind a
        // helper would otherwise leave a sweep that passes having read nothing.
        var tapOwnersWithoutInvalidate: [String] = []

        var tapOwners = 0

        let tapOwnerSources = FileManager.default
            .enumerator(atPath: "Sources/Vorssaint")?
            .compactMap { $0 as? String }
            .filter { $0.hasSuffix(".swift") && !$0.contains(" 2") } ?? []

        for file in tapOwnerSources.sorted() {
            guard let source = try? String(contentsOfFile: "Sources/Vorssaint/\(file)",
                                           encoding: .utf8) else { continue }
            let code = source.components(separatedBy: "\n")
                .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
                .joined(separator: "\n")
            let taps = code.components(separatedBy: "CGEvent.tapCreate").count - 1
            guard taps > 0 else { continue }
            tapOwners += 1
            // A tap served by the pointer thread is handed back there, which
            // is the same promise: `PointerTapRunLoop.remove` invalidates the
            // port it is given, and the sweep above pins that it does.
            let invalidations = code.components(separatedBy: "CFMachPortInvalidate").count - 1
                + (code.components(separatedBy: "PointerTapRunLoop.remove(").count - 1)
            if invalidations < taps {
                tapOwnersWithoutInvalidate.append("\(file) (\(taps) taps, \(invalidations) invalidated)")
            }
        }

        expect(tapOwners > 0 && tapOwnersWithoutInvalidate.isEmpty,
               "every event tap owner invalidates its port on teardown, across "
               + "\(tapOwners) scanned owners: \(tapOwnersWithoutInvalidate)")

        let mouseTapAppDelegateSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/App/AppDelegate.swift",
            encoding: .utf8)) ?? ""

        expect(mouseTapAppDelegateSource.contains("MouseButtonShortcutService.shared.suspend()"),
               "normal termination releases mouse-button tap state instead of waiting for a future Up")

        let accessibilitySink = mouseTapAppDelegateSource
            .components(separatedBy: "Permissions.shared.$accessibility")
            .dropFirst().first?.components(separatedBy: "Permissions.shared.$screenRecording").first ?? ""

        expect(accessibilitySink.contains(".quitWindowProtection"),
               "granting Accessibility starts quit protection without a relaunch")

        let smoothSchedulerSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/SmoothScrollService.swift",
            encoding: .utf8)) ?? ""

        let smoothSchedulerCode = smoothSchedulerSource.components(separatedBy: "\n")
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .joined(separator: "\n")

        let steppedLoupeBypass = smoothSchedulerCode
            .components(separatedBy: "if ScreenshotSelectionController.steppedLoupeNeedsRawWheel(")
            .dropFirst().first?.components(separatedBy: "return").first ?? ""

        expect(steppedLoupeBypass.contains("stopGlide()"),
               "entering stepped magnifier zoom cancels the fast glide before passing the raw notch")

        let scrollInverterSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/ScrollInverter.swift",
            encoding: .utf8)) ?? ""

        for (name, source) in [("scroll inverter", scrollInverterSource),
                               ("smooth scroll", smoothSchedulerCode)] {
            expect(source.contains("guard !tapCreationRetryUsed")
                    && source.contains("tapCreationRetryWork?.cancel()"),
                   "\(name) retries tap creation once instead of polling forever")
        }

        expect(smoothSchedulerCode.contains("screen.displayLink(")
                && smoothSchedulerCode.contains("displayLink.add(to: .main, forMode: .common)")
                && smoothSchedulerCode.contains("sender.timestamp")
                && smoothSchedulerCode.contains("sender.duration"),
               "smooth scrolling follows the active display's native cadence and elapsed frame time")

        expect(smoothSchedulerCode.contains("displayLink?.invalidate()")
                && smoothSchedulerCode.contains("frameTimer?.invalidate()")
                && smoothSchedulerCode.contains("removeScreenObserver()")
                && smoothSchedulerCode.contains("removeSleepObserver()"),
               "smooth scrolling releases either scheduler and its lifecycle observers on stop")

        expect(smoothSchedulerCode.contains("NSScreen.withMouse")
                && smoothSchedulerCode.contains("didChangeScreenParametersNotification")
                && smoothSchedulerCode.contains("Timer(timeInterval: SmoothScrollSupport.frameInterval"),
               "smooth scrolling follows display changes and keeps a no-screen timer fallback")

        let smoothTapDisabled = smoothSchedulerCode.components(separatedBy: "tapDisabledByTimeout")
            .dropFirst().first?.components(separatedBy: "return").first ?? ""

        expect(smoothTapDisabled.contains("tapDisabledByUserInput")
                && smoothTapDisabled.contains("stopGlide()")
                && smoothTapDisabled.contains("AppFeature.smoothScroll.isAvailable")
                && smoothTapDisabled.contains("DefaultsKey.smoothScrollEnabled")
                && smoothTapDisabled.contains("AXIsProcessTrusted()")
                && smoothTapDisabled.contains("SessionActivity.shared.isActive"),
               "a disabled smooth-scroll tap drops its tail and re-arms only while fully wanted")

        let smoothSleep = smoothSchedulerCode.components(separatedBy: "willSleepNotification")
            .dropFirst().first?.components(separatedBy: "private func removeSleepObserver").first ?? ""

        expect(smoothSleep.contains("stopGlide()"),
               "smooth scrolling cannot carry a pre-sleep glide into the next wake")

        let cleaningModeSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/CleaningMode/CleaningModeManager.swift",
            encoding: .utf8)) ?? ""

        expect(cleaningModeSource.contains("SessionActivity.shared.onChange")
                && cleaningModeSource.contains("deactivate(restoreSuspendedFeatures: false)")
                && cleaningModeSource.contains("SessionActivity.shared.isActive")
                && cleaningModeSource.contains("AXIsProcessTrusted()")
                && cleaningModeSource.contains("CFMachPortInvalidate"),
               "Cleaning Mode ends and releases its filter tap when the login session leaves the screen")

        print("[generated-checks] ModifyingMouseTapsAreHandedBackAcrossASessionSwitch \(checks)")
    }
}
