// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedScreenRecorderTextTests: XCTestCase {
    func testScreenRecorderText() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let caption = RecorderTextOverlay(text: "Hello", start: 2, end: 6)

        expect(caption.opacity(at: 1.9) == 0 && caption.opacity(at: 6.1) == 0,
               "text is not there before it starts or after it ends")

        expect(caption.opacity(at: 4) == 1, "text is solid in the middle of its own time")

        expect(caption.opacity(at: 2.1) > 0 && caption.opacity(at: 2.1) < 1,
               "text eases in instead of appearing on one frame")

        expect(caption.opacity(at: 5.9) > 0 && caption.opacity(at: 5.9) < 1,
               "text eases out the same way")

        let blink = RecorderTextOverlay(text: "Hi", start: 1, end: 1.3)

        expect(blink.opacity(at: 1.15) > 0,
               "a very short caption still gets to be visible at its middle")

        expect(RecorderTextOverlay(text: "x", start: 5, end: 5.05)
                .sanitized(duration: 10) == nil,
               "a caption too short to read is not kept")

        expect(RecorderTextOverlay(text: "x", start: 9, end: 30)
                .sanitized(duration: 10)?.end == 10,
               "a caption that runs past the recording is brought back inside it")

        expect(RecorderTextOverlay(text: "x", start: 1, end: 3, size: 9)
                .sanitized(duration: 10)?.size == RecorderTextOverlay.sizeRange.upperBound,
               "an impossible text size is clamped instead of filling the frame")

        print("[generated-checks] ScreenRecorderText \(checks)")
    }
}
