// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedMouseAppExceptionsIssue358Tests: XCTestCase {
    func testMouseAppExceptionsIssue358() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let exceptionSet: Set<String> = ["com.example.modeler"]

        if let regularBareApp, let resolvedRunningPath {
            expect(regularBareApp.identity == resolvedRunningPath
                    && regularBareApp.bundleID == nil
                    && regularBareApp.name == "java"
                    && regularBareApp.url.path == resolvedRunningPath,
                   "a running regular bare executable produces a path row with its resolved path identity")
        } else {
            expect(false, "a running regular bare executable resolves its path row setup")
        }

        if let wrapperBareApp, let resolvedWrapperPath {
            expect(wrapperBareApp.identity == resolvedWrapperPath
                    && wrapperBareApp.bundleID == nil
                    && wrapperBareApp.url.path == resolvedWrapperPath,
                   "a running executable inside a non-app wrapper produces a path row")
        } else {
            expect(false, "a non-app wrapper executable resolves its path row setup")
        }

        let appBundleURL = URL(fileURLWithPath: "/Applications/TextEdit.app")

        // Both ends of that agreement live outside this binary: the picker
        // stores from AppBundleList and the taps match from MouseAppExceptions.
        // An identity resolved at one end and taken raw at the other silently
        // matches nothing (issue #1009), so what each side may hand on is
        // pinned rather than the spelling it happens to use today — a second
        // way into the list, dropping a file onto it among them, has to go
        // through the same resolver as the sheet does.
        let pickerLines = ((try? String(
            contentsOfFile: "Sources/Vorssaint/UI/Settings/AppBundleList.swift",
            encoding: .utf8)) ?? "").components(separatedBy: "\n")

        var resolvedAddSites: [String] = []

        var rawAddSites: [String] = []

        for (index, line) in pickerLines.enumerated()

        where !line.trimmingCharacters(in: .whitespaces).hasPrefix("//") && line.contains("onAdd(") {
            let added = (line.components(separatedBy: "onAdd(").last?
                .components(separatedBy: ")").first ?? "").trimmingCharacters(in: .whitespaces)
            let nearbyLines = pickerLines[..<index].suffix(4)
            if nearbyLines.contains(where: {
                $0.contains("let \(added) =") && $0.contains("MouseAppExceptionSupport.")
            }) {
                resolvedAddSites.append("AppBundleList.swift:\(index + 1)")
            } else {
                rawAddSites.append("AppBundleList.swift:\(index + 1) adds \(added)")
            }
        }

        expect(!resolvedAddSites.isEmpty && rawAddSites.isEmpty,
               "every value the picker adds is one the support enum resolved: \(rawAddSites)")

        // A list row's location caption is what tells path identities apart —
        // every bundled runtime displays as "java" (issue #1009) — and sibling
        // runtimes differ only after a long shared directory prefix, so the
        // caption must truncate from the HEAD: cutting the middle or tail
        // would hide the one component that differs. Neither picker is
        // compiled into this binary, so their shapes are pinned here.
        let appPickerLines = ((try? String(
            contentsOfFile: "Sources/Vorssaint/UI/Uninstall/AppPickerView.swift",
            encoding: .utf8)) ?? "").components(separatedBy: "\n")

        let captionPickerLines = ["AppBundleList.swift": pickerLines,
                                  "AppPickerView.swift": appPickerLines]

        var captionFiles: [String] = []

        for (file, lines) in captionPickerLines {
            let sourceLines = lines.filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            if sourceLines.contains(where: { $0.contains("InstalledApps.location(for:") })
                && sourceLines.contains(where: { $0.contains(".truncationMode(") && $0.contains(".head") }) {
                captionFiles.append(file)
            }
        }

        expect(captionFiles.count == captionPickerLines.count,
               "each path identity picker shows where its file sits and truncates from the head: "
                   + "\(captionFiles)")

        var resolvedMatchSites: [String] = []

        var rawMatchSites: [String] = []

        let matcherLines = ((try? String(
            contentsOfFile: "Sources/Vorssaint/Services/MouseExceptions/MouseAppExceptions.swift",
            encoding: .utf8)) ?? "").components(separatedBy: "\n")

        for (index, line) in matcherLines.enumerated()

        where !line.trimmingCharacters(in: .whitespaces).hasPrefix("//")
                && line.contains("executableURL") && line.contains(".path") {
            if line.contains("MouseAppExceptionSupport.identity(")
                || (index > 0 && matcherLines[index - 1].contains("MouseAppExceptionSupport.identity(")) {
                resolvedMatchSites.append("MouseAppExceptions.swift:\(index + 1)")
            } else {
                rawMatchSites.append("MouseAppExceptions.swift:\(index + 1)")
            }
        }

        expect(resolvedMatchSites.count == 1 && rawMatchSites.isEmpty,
               "the taps read an executable path only through the support enum: "
                   + "\(resolvedMatchSites) \(rawMatchSites)")

        let matcherBody = matcherLines
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .joined(separator: "\n")

        expect(!matcherBody.isEmpty && !matcherBody.contains("trimmingCharacters"),
               "the exception list is sanitized through the one sanitizer, never beside it")

        // The leading-slash test IS the rule that tells a stored path from a
        // bundle identifier. A second spelling of it drifts the day the rule
        // learns a new shape — a ~ path, a file URL — so every file that
        // handles an identity asks isExecutablePathIdentity instead of
        // re-testing the prefix.
        var slashRuleSites: [String] = []

        for file in ["Services/MouseExceptions/MouseAppExceptionSupport.swift",
                     "Services/InstalledApps.swift",
                     "Core/Defaults.swift"] {
            let ruleLines = ((try? String(contentsOfFile: "Sources/Vorssaint/\(file)",
                                          encoding: .utf8)) ?? "").components(separatedBy: "\n")
            if ruleLines.count <= 1 { slashRuleSites.append("\(file) unreadable") }
            for (index, line) in ruleLines.enumerated()
            where !line.trimmingCharacters(in: .whitespaces).hasPrefix("//")
                    && line.contains("hasPrefix(\"/\")") {
                slashRuleSites.append("\(file):\(index + 1)")
            }
        }

        expect(slashRuleSites.count == 1
                && slashRuleSites[0].hasPrefix("Services/MouseExceptions/MouseAppExceptionSupport.swift:"),
               "the leading-slash rule is spelled once, inside isExecutablePathIdentity: \(slashRuleSites)")

        for language in AppLanguage.allCases {
            let strings = FeatureStrings.clipboardIgnoredApps(language)
            let values = Mirror(reflecting: strings).children.compactMap { $0.value as? String }
            expect(values.count == 4 && values.allSatisfy { !$0.isEmpty },
                   "every clipboard skip list string is set for \(language.rawValue)")
            expect(values.allSatisfy { !$0.contains("—") },
                   "no em-dash in visible clipboard skip list strings (\(language.rawValue))")
        }

        for language in AppLanguage.allCases {
            let strings = FeatureStrings.switcherAppRules(language)
            let values = Mirror(reflecting: strings).children.compactMap { $0.value as? String }
            expect(values.count == 8 && values.allSatisfy { !$0.isEmpty },
                   "every per-app switcher rule string is set for \(language.rawValue)")
            expect(values.allSatisfy { !$0.contains("—") },
                   "no em-dash in per-app switcher rule strings (\(language.rawValue))")
            expect(Set([strings.showWithoutWindows, strings.windowsOnly, strings.hidden]).count == 3,
                   "each per-app switcher choice is distinct for \(language.rawValue)")
        }

        expect(FinderRenameSupport.acceptsFocusedRole("AXOutline")
                && !FinderRenameSupport.acceptsFocusedRole("AXTextField")
                && !FinderRenameSupport.acceptsFocusedRole("AXTextArea")
                && !FinderRenameSupport.acceptsFocusedRole(nil),
               "Finder rename only acts outside editable fields with a known focus")

        for language in AppLanguage.allCases {
            let strings = FeatureStrings.windowPreviewExclusions(language)
            let values = Mirror(reflecting: strings).children.compactMap { $0.value as? String }
            expect(values.count == 5 && values.allSatisfy { !$0.isEmpty },
                   "every window preview exclusion string is set for \(language.rawValue)")
            expect(values.allSatisfy { !$0.contains("—") },
                   "no em-dash in visible window preview exclusion strings (\(language.rawValue))")
        }

        for language in AppLanguage.allCases {
            let strings = FeatureStrings.diskExclusions(language)
            let values = Mirror(reflecting: strings).children.compactMap { $0.value as? String }
            expect(values.count == 6 && values.allSatisfy { !$0.isEmpty },
                   "every disk exclusion string is set for \(language.rawValue)")
            expect(values.allSatisfy { !$0.contains("—") },
                   "no em-dash in visible disk exclusion strings (\(language.rawValue))")
        }

        for language in AppLanguage.allCases {
            let strings = WindowDirectionalStrings.localized(language)
            let values = Mirror(reflecting: strings).children.compactMap { $0.value as? String }
            expect(values.count == 2 && values.allSatisfy { !$0.isEmpty },
                   "every directional layout string is set for \(language.rawValue)")
            expect(values.allSatisfy { !$0.contains("—") },
                   "no em-dash in directional layout strings (\(language.rawValue))")
        }

        print("[generated-checks] MouseAppExceptionsIssue358 \(checks)")
    }
}
