// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/port-tests.py — do not edit.
// Source: Tests/MetricsTests.swift (WP-16, docs/linux-port/TESTS.md).
// Regenerate: python3 Tools/linux-port/port-tests.py

import Foundation
import XCTest
@testable import VorssaintCore


final class GeneratedCommandBarSearchAndRankingTests: XCTestCase {
    func testCommandBarSearchAndRanking() {
        var checks = 0
        func expect(_ condition: Bool, _ message: @autoclosure () -> String) {
            checks += 1
            XCTAssertTrue(condition, message())
        }
        func expectEqual(_ actual: String, _ expected: String, _ label: String) {
            checks += 1
            XCTAssertEqual(actual, expected, label)
        }
        func expectClose(_ actual: Double, _ expected: Double, _ label: String,
                         tol: Double = 0.0001) {
            checks += 1
            XCTAssertEqual(actual, expected, accuracy: tol, label)
        }
        func expectFormat(_ format: String, _ expected: [String], _ label: String) {
            checks += 1
            XCTAssertEqual(GeneratedSupport.formatSpecifiers(in: format), expected, label)
        }
        func placeholderShape(_ value: String) -> [String] {
            GeneratedSupport.placeholderShape(value)
        }
        func formatSpecifiers(in format: String) -> [String] {
            GeneratedSupport.formatSpecifiers(in: format)
        }

        let firstBarPresentation = UUID()

        let secondBarPresentation = UUID()

        let commandBarSource = (try? String(
            contentsOfFile: "Sources/Vorssaint/Services/CommandBar/CommandBarService.swift",
            encoding: .utf8)) ?? ""

        let commandBarCode = commandBarSource
            .split(separator: "\n", omittingEmptySubsequences: false)
            .filter { !$0.trimmingCharacters(in: .whitespaces).hasPrefix("//") }
            .joined(separator: "\n")

        let monitorParts = (commandBarCode
            .components(separatedBy: "private func installMonitors(for panel: NSPanel)")
            .last ?? "").components(separatedBy: "\n    private func ")

        let monitor = monitorParts.first ?? ""

        expect(monitorParts.count > 1
                && monitor.contains("? event.charactersIgnoringModifiers")
                && monitor.contains(": event.characters)?.lowercased()")
                && monitor.contains("let key = event.charactersIgnoringModifiers?.lowercased()")
                && !monitor.contains("case kVK_ANSI_Q")
                && monitor.contains("digitIndex(for: event.keyCode)"),
               "the Command Bar uses macOS Command letters while Control follows typed letters and digits stay positional")

        expect(monitor.contains("#selector(NSText.selectAll(_:))")
                && monitor.contains("#selector(NSText.copy(_:))")
                && monitor.contains("#selector(NSText.cut(_:))")
                && monitor.contains("#selector(NSText.paste(_:))")
                && monitor.contains("NSApp.sendAction"),
               "the Command Bar sends standard editing commands through its responder chain")

        // Ends on the next declaration rather than naming a neighbour: a
        // rename would find no separator, leave the slice running to end of
        // file, and quietly restore the whole-file search.
        let captureBeginParts = (commandBarCode
            .components(separatedBy: "private func beginCapturingShortcut(")
            .last ?? "").components(separatedBy: "\n    private func ")

        let captureBegin = captureBeginParts.first ?? ""

        expect(captureBeginParts.count > 1,
               "the Command Bar capture start finds the end of beginCapturingShortcut")

        expect(captureBegin.contains("ShortcutCapture.begin()")
                && captureBegin.contains("ShortcutRecordingTap.begin"),
               "the capture card starts the same pair Settings uses, so Command Q reaches it")

        let captureEndParts = (commandBarCode
            .components(separatedBy: "private func endCapturingShortcut()")
            .last ?? "").components(separatedBy: "\n    private func ")

        let captureEnd = captureEndParts.first ?? ""

        expect(captureEndParts.count > 1,
               "the Command Bar capture stop finds the end of endCapturingShortcut")

        expect(captureEnd.contains("ShortcutRecordingTap.end()")
                && captureEnd.contains("ShortcutCapture.end()"),
               "leaving the card gives the keyboard back")

        // Dates and places, answered by the calendar this Mac carries.
        var gregorian = Calendar(identifier: .gregorian)

        gregorian.timeZone = TimeZone(identifier: "UTC")!

        let english = Locale(identifier: "en_US")

        let tuesday = Date(timeIntervalSince1970: 1_785_240_000)   // 2026-07-28

        print("[generated-checks] CommandBarSearchAndRanking \(checks)")
    }
}
