#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Vorssaint
#
# WP-14: keep `Sources/VorssaintCore/Core/DefaultsKeyInventory.swift` in step
# with the key table in `DefaultsKeys.swift`.
#
# Swift cannot enumerate the `static let`s of an enum at run time, and the
# WP's acceptance criterion is a round trip over *every* key. So the list is
# generated from the one file that owns it, committed, and checked here.
#
#     python3 Tools/linux-port/defaults-inventory.py            # regenerate
#     python3 Tools/linux-port/defaults-inventory.py --verify   # CI gate
#
# `--verify` fails when the committed file is not what this tool produces,
# which is exactly the case "someone added a key and the round-trip test did
# not grow".

import argparse
import re
import sys

KEYS_FILE = "Sources/VorssaintCore/Core/DefaultsKeys.swift"
OUT_FILE = "Sources/VorssaintCore/Core/DefaultsKeyInventory.swift"

# `static let name = "value"`, the only shape the table uses. A key whose
# value is built at run time (`featureAvailable(_:)`) is a function and is
# handled separately by the inventory, which is why it is not matched here.
DECL = re.compile(r'^\s*static let ([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"([^"]*)"')

HEADER = '''// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint
//
// GENERATED by Tools/linux-port/defaults-inventory.py - do not edit.
// Source: Sources/VorssaintCore/Core/DefaultsKeys.swift (WP-14,
// docs/linux-port/SETTINGS.md).
// Regenerate: python3 Tools/linux-port/defaults-inventory.py

import Foundation

/// Every settings key the app stores, as data rather than as %d `static let`s.
///
/// Swift has no reflection over an enum's static members, so the round-trip
/// test WP-14 owes (`SettingsStoreTests`) cannot walk `DefaultsKey` itself.
/// This list is generated from `DefaultsKeys.swift` and checked in CI, so a
/// key added there and forgotten here fails the gate rather than quietly
/// falling out of the test.
enum DefaultsKeyInventory {
    /// The %d fixed keys, in declaration order.
    static let fixedKeys: [String] = [
%s
    ]

    /// The availability layer: one key per `AppFeature` raw value. The raw
    /// values live in the Mac layer's `FeatureCatalog.swift`, so the ids come
    /// from `FeatureSupportCatalog`, which owns them for the port.
    static var featureAvailabilityKeys: [String] {
        FeatureSupportCatalog.allFeatureIDs.map(DefaultsKey.featureAvailable)
    }

    /// Every key a settings store can be asked for.
    static var allKeys: [String] { fixedKeys + featureAvailabilityKeys }
}
'''


def read_keys(path):
    names, values, seen = [], [], {}
    with open(path, encoding="utf-8") as handle:
        for lineno, line in enumerate(handle, 1):
            match = DECL.match(line)
            if not match:
                continue
            name, value = match.group(1), match.group(2)
            if value in seen:
                sys.exit("%s:%d: duplicate key %r (also %s)"
                         % (path, lineno, value, seen[value]))
            seen[value] = name
            names.append(name)
            values.append(value)
    return names, values


def render(names):
    body = "\n".join("        DefaultsKey.%s," % name for name in names)
    return HEADER % (len(names), len(names), body)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--verify", action="store_true",
                        help="fail if the committed file is stale")
    args = parser.parse_args()

    names, _values = read_keys(KEYS_FILE)
    if not names:
        sys.exit("no keys found in %s" % KEYS_FILE)
    text = render(names)

    if args.verify:
        try:
            with open(OUT_FILE, encoding="utf-8") as handle:
                current = handle.read()
        except FileNotFoundError:
            sys.exit("%s is missing; run this tool without --verify" % OUT_FILE)
        if current != text:
            sys.exit("%s is stale: %d keys in %s; regenerate with "
                     "python3 Tools/linux-port/defaults-inventory.py"
                     % (OUT_FILE, len(names), KEYS_FILE))
        print("defaults inventory OK (%d fixed keys)" % len(names))
        return

    with open(OUT_FILE, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote %s (%d fixed keys)" % (OUT_FILE, len(names)))


if __name__ == "__main__":
    main()
