// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// One flavour of clipboard content.
///
/// A MIME type, because that is what Wayland's `wl_data_offer` and X11's
/// selection targets both speak, and what `NSPasteboard.PasteboardType`
/// already maps onto for the types this app reads (`public.utf8-plain-text`
/// is `text/plain;charset=utf-8`, `public.png` is `image/png`).
public struct ClipboardFlavor: RawRepresentable, Hashable, Codable {
    public let rawValue: String
    public init(rawValue: String) { self.rawValue = rawValue }
    public init(_ rawValue: String) { self.rawValue = rawValue }

    public static let utf8Text = ClipboardFlavor("text/plain;charset=utf-8")
    public static let html = ClipboardFlavor("text/html")
    public static let rtf = ClipboardFlavor("text/rtf")
    public static let png = ClipboardFlavor("image/png")
    public static let tiff = ClipboardFlavor("image/tiff")
    public static let fileList = ClipboardFlavor("text/uri-list")
}

/// One clipboard reading: every flavour the owner offered, at one instant.
public struct ClipboardContent: Equatable {
    public let flavors: [ClipboardFlavor: Data]
    /// The application that put it there, when the platform can say. Drives
    /// `ClipboardHistorySupport`'s ignored-apps list, which on macOS reads
    /// `NSPasteboard`'s owner and on Linux reads the focused toplevel's
    /// `app_id` at the moment of the change.
    public let sourceApplicationID: String?

    public init(flavors: [ClipboardFlavor: Data], sourceApplicationID: String? = nil) {
        self.flavors = flavors
        self.sourceApplicationID = sourceApplicationID
    }

    public var text: String? {
        flavors[.utf8Text].flatMap { String(data: $0, encoding: .utf8) }
    }
}

/// Reads and writes the clipboard, and says when it changed.
///
/// `ClipboardHistoryService` and the snippet, command-bar and shelf features
/// consume this. macOS polls `NSPasteboard.general.changeCount`; Linux uses
/// `ext_data_control_manager_v1` / `zwlr_data_control_manager_v1` where the
/// compositor has it (a real change *event*, not a poll), the clipboard portal
/// where it does not, and on GNOME the companion extension of `PLAN.md` § 4.6 —
/// which is why `capabilities` distinguishes watching from reading at all.
public protocol ClipboardAccess: PlatformService {
    /// The current clipboard, or `nil` when it is empty or unreadable.
    func read(flavors: [ClipboardFlavor]) -> ClipboardContent?

    /// Replaces the clipboard. `concealed` asks the platform to mark the entry
    /// as a password so other clipboard managers skip it (`x-kde-passwordManagerHint`
    /// on Linux, `NSPasteboardTypeAutoGenerated`/concealed on macOS).
    func write(_ content: ClipboardContent, concealed: Bool) throws

    func clear()

    /// Calls back on every clipboard change. The returned token stops it.
    /// Returns `nil` when `capabilities` lacks `.clipboardWatch`; callers then
    /// degrade to capturing on their own trigger rather than silently
    /// recording nothing.
    func watch(_ onChange: @escaping (ClipboardContent) -> Void) -> ClipboardWatchToken?

    func stopWatching(_ token: ClipboardWatchToken)

    /// The separate "selection" clipboard X11 and Wayland have and macOS does
    /// not. `nil` on a platform without one.
    func readPrimarySelection() -> ClipboardContent?
}

public struct ClipboardWatchToken: Hashable {
    public let rawValue: UInt64
    public init(rawValue: UInt64) { self.rawValue = rawValue }
}

public extension PlatformCapability {
    static let clipboardRead = PlatformCapability("clipboard.read")
    static let clipboardWrite = PlatformCapability("clipboard.write")
    /// Change notifications without polling.
    static let clipboardWatch = PlatformCapability("clipboard.watch")
    /// Can name the application that owns the current clipboard.
    static let clipboardSourceApplication = PlatformCapability("clipboard.sourceApplication")
    /// Has the X11/Wayland middle-click primary selection.
    static let clipboardPrimarySelection = PlatformCapability("clipboard.primarySelection")
    /// Can mark an entry as a password.
    static let clipboardConcealedEntries = PlatformCapability("clipboard.concealedEntries")
}
